// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dummy_proc_be.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dummy_proc_be::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dummy_proc_be::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dummy_proc_be::ap_ST_fsm_state1 = "1";
const sc_lv<3> dummy_proc_be::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> dummy_proc_be::ap_ST_fsm_state17 = "100";
const sc_lv<32> dummy_proc_be::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool dummy_proc_be::ap_const_boolean_1 = true;
const sc_lv<32> dummy_proc_be::ap_const_lv32_1 = "1";
const bool dummy_proc_be::ap_const_boolean_0 = false;
const sc_lv<1> dummy_proc_be::ap_const_lv1_0 = "0";
const sc_lv<1> dummy_proc_be::ap_const_lv1_1 = "1";
const sc_lv<11> dummy_proc_be::ap_const_lv11_0 = "00000000000";
const sc_lv<11> dummy_proc_be::ap_const_lv11_400 = "10000000000";
const sc_lv<11> dummy_proc_be::ap_const_lv11_1 = "1";
const sc_lv<16> dummy_proc_be::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> dummy_proc_be::ap_const_lv32_F = "1111";
const sc_lv<32> dummy_proc_be::ap_const_lv32_10 = "10000";
const sc_lv<32> dummy_proc_be::ap_const_lv32_1F = "11111";
const sc_lv<16> dummy_proc_be::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<32> dummy_proc_be::ap_const_lv32_FFFFFFE8 = "11111111111111111111111111101000";
const sc_lv<5> dummy_proc_be::ap_const_lv5_9 = "1001";
const sc_lv<31> dummy_proc_be::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<16> dummy_proc_be::ap_const_lv16_FFE8 = "1111111111101000";
const sc_lv<32> dummy_proc_be::ap_const_lv32_FFFFFFE7 = "11111111111111111111111111100111";
const sc_lv<32> dummy_proc_be::ap_const_lv32_19 = "11001";
const sc_lv<32> dummy_proc_be::ap_const_lv32_3F = "111111";
const sc_lv<8> dummy_proc_be::ap_const_lv8_7F = "1111111";
const sc_lv<8> dummy_proc_be::ap_const_lv8_7E = "1111110";
const sc_lv<8> dummy_proc_be::ap_const_lv8_1 = "1";
const sc_lv<32> dummy_proc_be::ap_const_lv32_17 = "10111";
const sc_lv<32> dummy_proc_be::ap_const_lv32_2 = "10";

dummy_proc_be::dummy_proc_be(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fft_top_fadd_32nsbkb_U4 = new fft_top_fadd_32nsbkb<1,5,32,32,32>("fft_top_fadd_32nsbkb_U4");
    fft_top_fadd_32nsbkb_U4->clk(ap_clk);
    fft_top_fadd_32nsbkb_U4->reset(ap_rst);
    fft_top_fadd_32nsbkb_U4->din0(tmp_reg_931);
    fft_top_fadd_32nsbkb_U4->din1(tmp_1_reg_936);
    fft_top_fadd_32nsbkb_U4->ce(grp_fu_140_ce);
    fft_top_fadd_32nsbkb_U4->dout(grp_fu_140_p2);
    fft_top_fmul_32nscud_U5 = new fft_top_fmul_32nscud<1,4,32,32,32>("fft_top_fmul_32nscud_U5");
    fft_top_fmul_32nscud_U5->clk(ap_clk);
    fft_top_fmul_32nscud_U5->reset(ap_rst);
    fft_top_fmul_32nscud_U5->din0(re_reg_919);
    fft_top_fmul_32nscud_U5->din1(re_reg_919);
    fft_top_fmul_32nscud_U5->ce(grp_fu_144_ce);
    fft_top_fmul_32nscud_U5->dout(grp_fu_144_p2);
    fft_top_fmul_32nscud_U6 = new fft_top_fmul_32nscud<1,4,32,32,32>("fft_top_fmul_32nscud_U6");
    fft_top_fmul_32nscud_U6->clk(ap_clk);
    fft_top_fmul_32nscud_U6->reset(ap_rst);
    fft_top_fmul_32nscud_U6->din0(im_reg_925);
    fft_top_fmul_32nscud_U6->din1(im_reg_925);
    fft_top_fmul_32nscud_U6->ce(grp_fu_148_ce);
    fft_top_fmul_32nscud_U6->dout(grp_fu_148_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_1_fu_542_p2);
    sensitive << ( icmp_ln947_2_fu_517_p2 );
    sensitive << ( icmp_ln947_3_fu_536_p2 );

    SC_METHOD(thread_a_fu_389_p2);
    sensitive << ( icmp_ln947_fu_364_p2 );
    sensitive << ( icmp_ln947_1_fu_383_p2 );

    SC_METHOD(thread_add_ln949_1_fu_561_p2);
    sensitive << ( trunc_ln944_1_reg_873 );

    SC_METHOD(thread_add_ln949_fu_408_p2);
    sensitive << ( trunc_ln944_reg_841 );

    SC_METHOD(thread_add_ln958_1_fu_604_p2);
    sensitive << ( sub_ln944_1_reg_867 );

    SC_METHOD(thread_add_ln958_fu_451_p2);
    sensitive << ( sub_ln944_reg_835 );

    SC_METHOD(thread_add_ln964_1_fu_740_p2);
    sensitive << ( sub_ln964_1_fu_735_p2 );
    sensitive << ( select_ln964_1_fu_728_p3 );

    SC_METHOD(thread_add_ln964_fu_685_p2);
    sensitive << ( sub_ln964_fu_680_p2 );
    sensitive << ( select_ln964_fu_673_p3 );

    SC_METHOD(thread_and_ln949_1_fu_573_p2);
    sensitive << ( p_Result_10_fu_566_p3 );
    sensitive << ( xor_ln949_1_fu_555_p2 );

    SC_METHOD(thread_and_ln949_fu_420_p2);
    sensitive << ( p_Result_4_fu_413_p3 );
    sensitive << ( xor_ln949_fu_402_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_r_empty_n );
    sensitive << ( out_r_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);
    sensitive << ( out_r_full_n );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( in_r_empty_n );
    sensitive << ( icmp_ln24_reg_780 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln24_fu_152_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_bitcast_ln739_1_fu_769_p1);
    sensitive << ( trunc_ln738_1_fu_765_p1 );

    SC_METHOD(thread_bitcast_ln739_fu_714_p1);
    sensitive << ( trunc_ln738_fu_710_p1 );

    SC_METHOD(thread_grp_fu_140_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_144_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_148_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_158_p2);
    sensitive << ( i_0_reg_129 );

    SC_METHOD(thread_icmp_ln24_fu_152_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_0_reg_129 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln935_1_fu_216_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_8_fu_206_p4 );

    SC_METHOD(thread_icmp_ln935_fu_168_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_6_fu_164_p1 );

    SC_METHOD(thread_icmp_ln947_1_fu_383_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_789_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( p_Result_3_fu_378_p2 );

    SC_METHOD(thread_icmp_ln947_2_fu_517_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_812_pp0_iter2_reg );
    sensitive << ( tmp_11_reg_884 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln947_3_fu_536_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_812_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( p_Result_9_fu_531_p2 );

    SC_METHOD(thread_icmp_ln947_fu_364_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_789_pp0_iter2_reg );
    sensitive << ( tmp_6_reg_852 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln958_1_fu_599_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_812_pp0_iter2_reg );
    sensitive << ( lsb_index_1_reg_878 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln958_fu_446_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_789_pp0_iter2_reg );
    sensitive << ( lsb_index_reg_846 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_im_fu_773_p3);
    sensitive << ( icmp_ln935_1_reg_812_pp0_iter3_reg );
    sensitive << ( bitcast_ln739_1_fu_769_p1 );

    SC_METHOD(thread_in_r_blk_n);
    sensitive << ( in_r_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln24_reg_780 );

    SC_METHOD(thread_in_r_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln24_reg_780 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_l_1_fu_316_p3);
    sensitive << ( p_Result_16_fu_309_p3 );

    SC_METHOD(thread_l_fu_261_p3);
    sensitive << ( p_Result_13_fu_254_p3 );

    SC_METHOD(thread_lsb_index_1_fu_334_p2);
    sensitive << ( sub_ln944_1_fu_324_p2 );

    SC_METHOD(thread_lsb_index_fu_279_p2);
    sensitive << ( sub_ln944_fu_269_p2 );

    SC_METHOD(thread_lshr_ln947_1_fu_525_p2);
    sensitive << ( zext_ln947_1_fu_522_p1 );

    SC_METHOD(thread_lshr_ln947_fu_372_p2);
    sensitive << ( zext_ln947_fu_369_p1 );

    SC_METHOD(thread_lshr_ln958_1_fu_609_p2);
    sensitive << ( zext_ln957_2_fu_596_p1 );
    sensitive << ( add_ln958_1_fu_604_p2 );

    SC_METHOD(thread_lshr_ln958_fu_456_p2);
    sensitive << ( zext_ln957_1_fu_443_p1 );
    sensitive << ( add_ln958_fu_451_p2 );

    SC_METHOD(thread_m_10_fu_634_p3);
    sensitive << ( icmp_ln958_1_fu_599_p2 );
    sensitive << ( zext_ln958_2_fu_615_p1 );
    sensitive << ( shl_ln958_1_fu_628_p2 );

    SC_METHOD(thread_m_12_fu_646_p2);
    sensitive << ( zext_ln961_1_fu_642_p1 );
    sensitive << ( m_10_fu_634_p3 );

    SC_METHOD(thread_m_15_fu_670_p1);
    sensitive << ( m_s_reg_899 );

    SC_METHOD(thread_m_16_fu_725_p1);
    sensitive << ( m_3_reg_909 );

    SC_METHOD(thread_m_1_fu_481_p3);
    sensitive << ( icmp_ln958_fu_446_p2 );
    sensitive << ( zext_ln958_fu_462_p1 );
    sensitive << ( shl_ln958_fu_475_p2 );

    SC_METHOD(thread_m_2_fu_493_p2);
    sensitive << ( zext_ln961_fu_489_p1 );
    sensitive << ( m_1_fu_481_p3 );

    SC_METHOD(thread_m_9_fu_593_p1);
    sensitive << ( tmp_V_9_reg_822_pp0_iter2_reg );

    SC_METHOD(thread_m_fu_440_p1);
    sensitive << ( tmp_V_7_reg_799_pp0_iter2_reg );

    SC_METHOD(thread_or_ln949_1_fu_585_p3);
    sensitive << ( or_ln949_fu_579_p2 );

    SC_METHOD(thread_or_ln949_2_fu_426_p2);
    sensitive << ( and_ln949_fu_420_p2 );
    sensitive << ( a_fu_389_p2 );

    SC_METHOD(thread_or_ln949_fu_579_p2);
    sensitive << ( and_ln949_1_fu_573_p2 );
    sensitive << ( a_1_fu_542_p2 );

    SC_METHOD(thread_or_ln_fu_432_p3);
    sensitive << ( or_ln949_2_fu_426_p2 );

    SC_METHOD(thread_out_r_blk_n);
    sensitive << ( out_r_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );

    SC_METHOD(thread_out_r_din);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );
    sensitive << ( tmp_2_reg_941 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_r_write);
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_reg_780_pp0_iter13_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_Result_10_fu_566_p3);
    sensitive << ( tmp_V_9_reg_822_pp0_iter2_reg );
    sensitive << ( add_ln949_1_fu_561_p2 );

    SC_METHOD(thread_p_Result_12_fu_174_p3);
    sensitive << ( in_r_dout );

    SC_METHOD(thread_p_Result_13_fu_254_p3);
    sensitive << ( p_Result_s_reg_807 );

    SC_METHOD(thread_p_Result_14_fu_698_p5);
    sensitive << ( m_15_fu_670_p1 );
    sensitive << ( tmp_5_fu_691_p3 );

    SC_METHOD(thread_p_Result_15_fu_222_p3);
    sensitive << ( in_r_dout );

    SC_METHOD(thread_p_Result_16_fu_309_p3);
    sensitive << ( p_Result_7_reg_830 );

    SC_METHOD(thread_p_Result_17_fu_753_p5);
    sensitive << ( m_16_fu_725_p1 );
    sensitive << ( tmp_7_fu_746_p3 );

    SC_METHOD(thread_p_Result_3_fu_378_p2);
    sensitive << ( tmp_V_7_reg_799_pp0_iter2_reg );
    sensitive << ( lshr_ln947_fu_372_p2 );

    SC_METHOD(thread_p_Result_4_fu_413_p3);
    sensitive << ( tmp_V_7_reg_799_pp0_iter2_reg );
    sensitive << ( add_ln949_fu_408_p2 );

    SC_METHOD(thread_p_Result_7_fu_244_p4);
    sensitive << ( tmp_V_9_fu_236_p3 );

    SC_METHOD(thread_p_Result_9_fu_531_p2);
    sensitive << ( tmp_V_9_reg_822_pp0_iter2_reg );
    sensitive << ( lshr_ln947_1_fu_525_p2 );

    SC_METHOD(thread_p_Result_s_fu_196_p4);
    sensitive << ( tmp_V_7_fu_188_p3 );

    SC_METHOD(thread_re_fu_718_p3);
    sensitive << ( icmp_ln935_reg_789_pp0_iter3_reg );
    sensitive << ( bitcast_ln739_fu_714_p1 );

    SC_METHOD(thread_select_ln964_1_fu_728_p3);
    sensitive << ( tmp_13_reg_914 );

    SC_METHOD(thread_select_ln964_fu_673_p3);
    sensitive << ( tmp_9_reg_904 );

    SC_METHOD(thread_shl_ln958_1_fu_628_p2);
    sensitive << ( m_9_fu_593_p1 );
    sensitive << ( zext_ln958_3_fu_624_p1 );

    SC_METHOD(thread_shl_ln958_fu_475_p2);
    sensitive << ( m_fu_440_p1 );
    sensitive << ( zext_ln958_1_fu_471_p1 );

    SC_METHOD(thread_sub_ln944_1_fu_324_p2);
    sensitive << ( l_1_fu_316_p3 );

    SC_METHOD(thread_sub_ln944_fu_269_p2);
    sensitive << ( l_fu_261_p3 );

    SC_METHOD(thread_sub_ln947_1_fu_354_p2);
    sensitive << ( trunc_ln947_1_fu_350_p1 );

    SC_METHOD(thread_sub_ln947_fu_299_p2);
    sensitive << ( trunc_ln947_fu_295_p1 );

    SC_METHOD(thread_sub_ln958_1_fu_619_p2);
    sensitive << ( sub_ln944_1_reg_867 );

    SC_METHOD(thread_sub_ln958_fu_466_p2);
    sensitive << ( sub_ln944_reg_835 );

    SC_METHOD(thread_sub_ln964_1_fu_735_p2);
    sensitive << ( trunc_ln943_1_reg_894_pp0_iter3_reg );

    SC_METHOD(thread_sub_ln964_fu_680_p2);
    sensitive << ( trunc_ln943_reg_862_pp0_iter3_reg );

    SC_METHOD(thread_tmp_12_fu_548_p3);
    sensitive << ( lsb_index_1_reg_878 );

    SC_METHOD(thread_tmp_5_fu_691_p3);
    sensitive << ( p_Result_12_reg_794_pp0_iter3_reg );
    sensitive << ( add_ln964_fu_685_p2 );

    SC_METHOD(thread_tmp_7_fu_746_p3);
    sensitive << ( p_Result_15_reg_817_pp0_iter3_reg );
    sensitive << ( add_ln964_1_fu_740_p2 );

    SC_METHOD(thread_tmp_8_fu_395_p3);
    sensitive << ( lsb_index_reg_846 );

    SC_METHOD(thread_tmp_V_4_fu_230_p2);
    sensitive << ( tmp_V_8_fu_206_p4 );

    SC_METHOD(thread_tmp_V_6_fu_164_p1);
    sensitive << ( in_r_dout );

    SC_METHOD(thread_tmp_V_7_fu_188_p3);
    sensitive << ( p_Result_12_fu_174_p3 );
    sensitive << ( tmp_V_6_fu_164_p1 );
    sensitive << ( tmp_V_fu_182_p2 );

    SC_METHOD(thread_tmp_V_8_fu_206_p4);
    sensitive << ( in_r_dout );

    SC_METHOD(thread_tmp_V_9_fu_236_p3);
    sensitive << ( p_Result_15_fu_222_p3 );
    sensitive << ( tmp_V_8_fu_206_p4 );
    sensitive << ( tmp_V_4_fu_230_p2 );

    SC_METHOD(thread_tmp_V_fu_182_p2);
    sensitive << ( tmp_V_6_fu_164_p1 );

    SC_METHOD(thread_trunc_ln738_1_fu_765_p1);
    sensitive << ( p_Result_17_fu_753_p5 );

    SC_METHOD(thread_trunc_ln738_fu_710_p1);
    sensitive << ( p_Result_14_fu_698_p5 );

    SC_METHOD(thread_trunc_ln943_1_fu_360_p1);
    sensitive << ( l_1_fu_316_p3 );

    SC_METHOD(thread_trunc_ln943_fu_305_p1);
    sensitive << ( l_fu_261_p3 );

    SC_METHOD(thread_trunc_ln944_1_fu_330_p1);
    sensitive << ( sub_ln944_1_fu_324_p2 );

    SC_METHOD(thread_trunc_ln944_fu_275_p1);
    sensitive << ( sub_ln944_fu_269_p2 );

    SC_METHOD(thread_trunc_ln947_1_fu_350_p1);
    sensitive << ( sub_ln944_1_fu_324_p2 );

    SC_METHOD(thread_trunc_ln947_fu_295_p1);
    sensitive << ( sub_ln944_fu_269_p2 );

    SC_METHOD(thread_xor_ln949_1_fu_555_p2);
    sensitive << ( tmp_12_fu_548_p3 );

    SC_METHOD(thread_xor_ln949_fu_402_p2);
    sensitive << ( tmp_8_fu_395_p3 );

    SC_METHOD(thread_zext_ln947_1_fu_522_p1);
    sensitive << ( sub_ln947_1_reg_889 );

    SC_METHOD(thread_zext_ln947_fu_369_p1);
    sensitive << ( sub_ln947_reg_857 );

    SC_METHOD(thread_zext_ln957_1_fu_443_p1);
    sensitive << ( tmp_V_7_reg_799_pp0_iter2_reg );

    SC_METHOD(thread_zext_ln957_2_fu_596_p1);
    sensitive << ( tmp_V_9_reg_822_pp0_iter2_reg );

    SC_METHOD(thread_zext_ln958_1_fu_471_p1);
    sensitive << ( sub_ln958_fu_466_p2 );

    SC_METHOD(thread_zext_ln958_2_fu_615_p1);
    sensitive << ( lshr_ln958_1_fu_609_p2 );

    SC_METHOD(thread_zext_ln958_3_fu_624_p1);
    sensitive << ( sub_ln958_1_fu_619_p2 );

    SC_METHOD(thread_zext_ln958_fu_462_p1);
    sensitive << ( lshr_ln958_fu_456_p2 );

    SC_METHOD(thread_zext_ln961_1_fu_642_p1);
    sensitive << ( or_ln949_1_fu_585_p3 );

    SC_METHOD(thread_zext_ln961_fu_489_p1);
    sensitive << ( or_ln_fu_432_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( icmp_ln24_fu_152_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter13 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dummy_proc_be_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_dout, "(port)in_r_dout");
    sc_trace(mVcdFile, in_r_empty_n, "(port)in_r_empty_n");
    sc_trace(mVcdFile, in_r_read, "(port)in_r_read");
    sc_trace(mVcdFile, out_r_din, "(port)out_r_din");
    sc_trace(mVcdFile, out_r_full_n, "(port)out_r_full_n");
    sc_trace(mVcdFile, out_r_write, "(port)out_r_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_r_blk_n, "in_r_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln24_reg_780, "icmp_ln24_reg_780");
    sc_trace(mVcdFile, out_r_blk_n, "out_r_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter13_reg, "icmp_ln24_reg_780_pp0_iter13_reg");
    sc_trace(mVcdFile, i_0_reg_129, "i_0_reg_129");
    sc_trace(mVcdFile, icmp_ln24_fu_152_p2, "icmp_ln24_fu_152_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter1_reg, "icmp_ln24_reg_780_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter2_reg, "icmp_ln24_reg_780_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter3_reg, "icmp_ln24_reg_780_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter4_reg, "icmp_ln24_reg_780_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter5_reg, "icmp_ln24_reg_780_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter6_reg, "icmp_ln24_reg_780_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter7_reg, "icmp_ln24_reg_780_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter8_reg, "icmp_ln24_reg_780_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter9_reg, "icmp_ln24_reg_780_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter10_reg, "icmp_ln24_reg_780_pp0_iter10_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter11_reg, "icmp_ln24_reg_780_pp0_iter11_reg");
    sc_trace(mVcdFile, icmp_ln24_reg_780_pp0_iter12_reg, "icmp_ln24_reg_780_pp0_iter12_reg");
    sc_trace(mVcdFile, i_fu_158_p2, "i_fu_158_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, icmp_ln935_fu_168_p2, "icmp_ln935_fu_168_p2");
    sc_trace(mVcdFile, icmp_ln935_reg_789, "icmp_ln935_reg_789");
    sc_trace(mVcdFile, icmp_ln935_reg_789_pp0_iter2_reg, "icmp_ln935_reg_789_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln935_reg_789_pp0_iter3_reg, "icmp_ln935_reg_789_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_12_fu_174_p3, "p_Result_12_fu_174_p3");
    sc_trace(mVcdFile, p_Result_12_reg_794, "p_Result_12_reg_794");
    sc_trace(mVcdFile, p_Result_12_reg_794_pp0_iter2_reg, "p_Result_12_reg_794_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_12_reg_794_pp0_iter3_reg, "p_Result_12_reg_794_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_V_7_fu_188_p3, "tmp_V_7_fu_188_p3");
    sc_trace(mVcdFile, tmp_V_7_reg_799, "tmp_V_7_reg_799");
    sc_trace(mVcdFile, tmp_V_7_reg_799_pp0_iter2_reg, "tmp_V_7_reg_799_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_s_fu_196_p4, "p_Result_s_fu_196_p4");
    sc_trace(mVcdFile, p_Result_s_reg_807, "p_Result_s_reg_807");
    sc_trace(mVcdFile, icmp_ln935_1_fu_216_p2, "icmp_ln935_1_fu_216_p2");
    sc_trace(mVcdFile, icmp_ln935_1_reg_812, "icmp_ln935_1_reg_812");
    sc_trace(mVcdFile, icmp_ln935_1_reg_812_pp0_iter2_reg, "icmp_ln935_1_reg_812_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln935_1_reg_812_pp0_iter3_reg, "icmp_ln935_1_reg_812_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_15_fu_222_p3, "p_Result_15_fu_222_p3");
    sc_trace(mVcdFile, p_Result_15_reg_817, "p_Result_15_reg_817");
    sc_trace(mVcdFile, p_Result_15_reg_817_pp0_iter2_reg, "p_Result_15_reg_817_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_15_reg_817_pp0_iter3_reg, "p_Result_15_reg_817_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_V_9_fu_236_p3, "tmp_V_9_fu_236_p3");
    sc_trace(mVcdFile, tmp_V_9_reg_822, "tmp_V_9_reg_822");
    sc_trace(mVcdFile, tmp_V_9_reg_822_pp0_iter2_reg, "tmp_V_9_reg_822_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_7_fu_244_p4, "p_Result_7_fu_244_p4");
    sc_trace(mVcdFile, p_Result_7_reg_830, "p_Result_7_reg_830");
    sc_trace(mVcdFile, sub_ln944_fu_269_p2, "sub_ln944_fu_269_p2");
    sc_trace(mVcdFile, sub_ln944_reg_835, "sub_ln944_reg_835");
    sc_trace(mVcdFile, trunc_ln944_fu_275_p1, "trunc_ln944_fu_275_p1");
    sc_trace(mVcdFile, trunc_ln944_reg_841, "trunc_ln944_reg_841");
    sc_trace(mVcdFile, lsb_index_fu_279_p2, "lsb_index_fu_279_p2");
    sc_trace(mVcdFile, lsb_index_reg_846, "lsb_index_reg_846");
    sc_trace(mVcdFile, tmp_6_reg_852, "tmp_6_reg_852");
    sc_trace(mVcdFile, sub_ln947_fu_299_p2, "sub_ln947_fu_299_p2");
    sc_trace(mVcdFile, sub_ln947_reg_857, "sub_ln947_reg_857");
    sc_trace(mVcdFile, trunc_ln943_fu_305_p1, "trunc_ln943_fu_305_p1");
    sc_trace(mVcdFile, trunc_ln943_reg_862, "trunc_ln943_reg_862");
    sc_trace(mVcdFile, trunc_ln943_reg_862_pp0_iter3_reg, "trunc_ln943_reg_862_pp0_iter3_reg");
    sc_trace(mVcdFile, sub_ln944_1_fu_324_p2, "sub_ln944_1_fu_324_p2");
    sc_trace(mVcdFile, sub_ln944_1_reg_867, "sub_ln944_1_reg_867");
    sc_trace(mVcdFile, trunc_ln944_1_fu_330_p1, "trunc_ln944_1_fu_330_p1");
    sc_trace(mVcdFile, trunc_ln944_1_reg_873, "trunc_ln944_1_reg_873");
    sc_trace(mVcdFile, lsb_index_1_fu_334_p2, "lsb_index_1_fu_334_p2");
    sc_trace(mVcdFile, lsb_index_1_reg_878, "lsb_index_1_reg_878");
    sc_trace(mVcdFile, tmp_11_reg_884, "tmp_11_reg_884");
    sc_trace(mVcdFile, sub_ln947_1_fu_354_p2, "sub_ln947_1_fu_354_p2");
    sc_trace(mVcdFile, sub_ln947_1_reg_889, "sub_ln947_1_reg_889");
    sc_trace(mVcdFile, trunc_ln943_1_fu_360_p1, "trunc_ln943_1_fu_360_p1");
    sc_trace(mVcdFile, trunc_ln943_1_reg_894, "trunc_ln943_1_reg_894");
    sc_trace(mVcdFile, trunc_ln943_1_reg_894_pp0_iter3_reg, "trunc_ln943_1_reg_894_pp0_iter3_reg");
    sc_trace(mVcdFile, m_s_reg_899, "m_s_reg_899");
    sc_trace(mVcdFile, tmp_9_reg_904, "tmp_9_reg_904");
    sc_trace(mVcdFile, m_3_reg_909, "m_3_reg_909");
    sc_trace(mVcdFile, tmp_13_reg_914, "tmp_13_reg_914");
    sc_trace(mVcdFile, re_fu_718_p3, "re_fu_718_p3");
    sc_trace(mVcdFile, re_reg_919, "re_reg_919");
    sc_trace(mVcdFile, im_fu_773_p3, "im_fu_773_p3");
    sc_trace(mVcdFile, im_reg_925, "im_reg_925");
    sc_trace(mVcdFile, grp_fu_144_p2, "grp_fu_144_p2");
    sc_trace(mVcdFile, tmp_reg_931, "tmp_reg_931");
    sc_trace(mVcdFile, grp_fu_148_p2, "grp_fu_148_p2");
    sc_trace(mVcdFile, tmp_1_reg_936, "tmp_1_reg_936");
    sc_trace(mVcdFile, grp_fu_140_p2, "grp_fu_140_p2");
    sc_trace(mVcdFile, tmp_2_reg_941, "tmp_2_reg_941");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp_V_6_fu_164_p1, "tmp_V_6_fu_164_p1");
    sc_trace(mVcdFile, tmp_V_fu_182_p2, "tmp_V_fu_182_p2");
    sc_trace(mVcdFile, tmp_V_8_fu_206_p4, "tmp_V_8_fu_206_p4");
    sc_trace(mVcdFile, tmp_V_4_fu_230_p2, "tmp_V_4_fu_230_p2");
    sc_trace(mVcdFile, p_Result_13_fu_254_p3, "p_Result_13_fu_254_p3");
    sc_trace(mVcdFile, l_fu_261_p3, "l_fu_261_p3");
    sc_trace(mVcdFile, trunc_ln947_fu_295_p1, "trunc_ln947_fu_295_p1");
    sc_trace(mVcdFile, p_Result_16_fu_309_p3, "p_Result_16_fu_309_p3");
    sc_trace(mVcdFile, l_1_fu_316_p3, "l_1_fu_316_p3");
    sc_trace(mVcdFile, trunc_ln947_1_fu_350_p1, "trunc_ln947_1_fu_350_p1");
    sc_trace(mVcdFile, zext_ln947_fu_369_p1, "zext_ln947_fu_369_p1");
    sc_trace(mVcdFile, lshr_ln947_fu_372_p2, "lshr_ln947_fu_372_p2");
    sc_trace(mVcdFile, p_Result_3_fu_378_p2, "p_Result_3_fu_378_p2");
    sc_trace(mVcdFile, icmp_ln947_fu_364_p2, "icmp_ln947_fu_364_p2");
    sc_trace(mVcdFile, icmp_ln947_1_fu_383_p2, "icmp_ln947_1_fu_383_p2");
    sc_trace(mVcdFile, tmp_8_fu_395_p3, "tmp_8_fu_395_p3");
    sc_trace(mVcdFile, add_ln949_fu_408_p2, "add_ln949_fu_408_p2");
    sc_trace(mVcdFile, p_Result_4_fu_413_p3, "p_Result_4_fu_413_p3");
    sc_trace(mVcdFile, xor_ln949_fu_402_p2, "xor_ln949_fu_402_p2");
    sc_trace(mVcdFile, and_ln949_fu_420_p2, "and_ln949_fu_420_p2");
    sc_trace(mVcdFile, a_fu_389_p2, "a_fu_389_p2");
    sc_trace(mVcdFile, or_ln949_2_fu_426_p2, "or_ln949_2_fu_426_p2");
    sc_trace(mVcdFile, zext_ln957_1_fu_443_p1, "zext_ln957_1_fu_443_p1");
    sc_trace(mVcdFile, add_ln958_fu_451_p2, "add_ln958_fu_451_p2");
    sc_trace(mVcdFile, lshr_ln958_fu_456_p2, "lshr_ln958_fu_456_p2");
    sc_trace(mVcdFile, sub_ln958_fu_466_p2, "sub_ln958_fu_466_p2");
    sc_trace(mVcdFile, m_fu_440_p1, "m_fu_440_p1");
    sc_trace(mVcdFile, zext_ln958_1_fu_471_p1, "zext_ln958_1_fu_471_p1");
    sc_trace(mVcdFile, icmp_ln958_fu_446_p2, "icmp_ln958_fu_446_p2");
    sc_trace(mVcdFile, zext_ln958_fu_462_p1, "zext_ln958_fu_462_p1");
    sc_trace(mVcdFile, shl_ln958_fu_475_p2, "shl_ln958_fu_475_p2");
    sc_trace(mVcdFile, or_ln_fu_432_p3, "or_ln_fu_432_p3");
    sc_trace(mVcdFile, zext_ln961_fu_489_p1, "zext_ln961_fu_489_p1");
    sc_trace(mVcdFile, m_1_fu_481_p3, "m_1_fu_481_p3");
    sc_trace(mVcdFile, m_2_fu_493_p2, "m_2_fu_493_p2");
    sc_trace(mVcdFile, zext_ln947_1_fu_522_p1, "zext_ln947_1_fu_522_p1");
    sc_trace(mVcdFile, lshr_ln947_1_fu_525_p2, "lshr_ln947_1_fu_525_p2");
    sc_trace(mVcdFile, p_Result_9_fu_531_p2, "p_Result_9_fu_531_p2");
    sc_trace(mVcdFile, icmp_ln947_2_fu_517_p2, "icmp_ln947_2_fu_517_p2");
    sc_trace(mVcdFile, icmp_ln947_3_fu_536_p2, "icmp_ln947_3_fu_536_p2");
    sc_trace(mVcdFile, tmp_12_fu_548_p3, "tmp_12_fu_548_p3");
    sc_trace(mVcdFile, add_ln949_1_fu_561_p2, "add_ln949_1_fu_561_p2");
    sc_trace(mVcdFile, p_Result_10_fu_566_p3, "p_Result_10_fu_566_p3");
    sc_trace(mVcdFile, xor_ln949_1_fu_555_p2, "xor_ln949_1_fu_555_p2");
    sc_trace(mVcdFile, and_ln949_1_fu_573_p2, "and_ln949_1_fu_573_p2");
    sc_trace(mVcdFile, a_1_fu_542_p2, "a_1_fu_542_p2");
    sc_trace(mVcdFile, or_ln949_fu_579_p2, "or_ln949_fu_579_p2");
    sc_trace(mVcdFile, zext_ln957_2_fu_596_p1, "zext_ln957_2_fu_596_p1");
    sc_trace(mVcdFile, add_ln958_1_fu_604_p2, "add_ln958_1_fu_604_p2");
    sc_trace(mVcdFile, lshr_ln958_1_fu_609_p2, "lshr_ln958_1_fu_609_p2");
    sc_trace(mVcdFile, sub_ln958_1_fu_619_p2, "sub_ln958_1_fu_619_p2");
    sc_trace(mVcdFile, m_9_fu_593_p1, "m_9_fu_593_p1");
    sc_trace(mVcdFile, zext_ln958_3_fu_624_p1, "zext_ln958_3_fu_624_p1");
    sc_trace(mVcdFile, icmp_ln958_1_fu_599_p2, "icmp_ln958_1_fu_599_p2");
    sc_trace(mVcdFile, zext_ln958_2_fu_615_p1, "zext_ln958_2_fu_615_p1");
    sc_trace(mVcdFile, shl_ln958_1_fu_628_p2, "shl_ln958_1_fu_628_p2");
    sc_trace(mVcdFile, or_ln949_1_fu_585_p3, "or_ln949_1_fu_585_p3");
    sc_trace(mVcdFile, zext_ln961_1_fu_642_p1, "zext_ln961_1_fu_642_p1");
    sc_trace(mVcdFile, m_10_fu_634_p3, "m_10_fu_634_p3");
    sc_trace(mVcdFile, m_12_fu_646_p2, "m_12_fu_646_p2");
    sc_trace(mVcdFile, sub_ln964_fu_680_p2, "sub_ln964_fu_680_p2");
    sc_trace(mVcdFile, select_ln964_fu_673_p3, "select_ln964_fu_673_p3");
    sc_trace(mVcdFile, add_ln964_fu_685_p2, "add_ln964_fu_685_p2");
    sc_trace(mVcdFile, m_15_fu_670_p1, "m_15_fu_670_p1");
    sc_trace(mVcdFile, tmp_5_fu_691_p3, "tmp_5_fu_691_p3");
    sc_trace(mVcdFile, p_Result_14_fu_698_p5, "p_Result_14_fu_698_p5");
    sc_trace(mVcdFile, trunc_ln738_fu_710_p1, "trunc_ln738_fu_710_p1");
    sc_trace(mVcdFile, bitcast_ln739_fu_714_p1, "bitcast_ln739_fu_714_p1");
    sc_trace(mVcdFile, sub_ln964_1_fu_735_p2, "sub_ln964_1_fu_735_p2");
    sc_trace(mVcdFile, select_ln964_1_fu_728_p3, "select_ln964_1_fu_728_p3");
    sc_trace(mVcdFile, add_ln964_1_fu_740_p2, "add_ln964_1_fu_740_p2");
    sc_trace(mVcdFile, m_16_fu_725_p1, "m_16_fu_725_p1");
    sc_trace(mVcdFile, tmp_7_fu_746_p3, "tmp_7_fu_746_p3");
    sc_trace(mVcdFile, p_Result_17_fu_753_p5, "p_Result_17_fu_753_p5");
    sc_trace(mVcdFile, trunc_ln738_1_fu_765_p1, "trunc_ln738_1_fu_765_p1");
    sc_trace(mVcdFile, bitcast_ln739_1_fu_769_p1, "bitcast_ln739_1_fu_769_p1");
    sc_trace(mVcdFile, grp_fu_140_ce, "grp_fu_140_ce");
    sc_trace(mVcdFile, grp_fu_144_ce, "grp_fu_144_ce");
    sc_trace(mVcdFile, grp_fu_148_ce, "grp_fu_148_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

dummy_proc_be::~dummy_proc_be() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete fft_top_fadd_32nsbkb_U4;
    delete fft_top_fmul_32nscud_U5;
    delete fft_top_fmul_32nscud_U6;
}

void dummy_proc_be::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter14 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_fu_152_p2.read()))) {
        i_0_reg_129 = i_fu_158_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_129 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln24_reg_780 = icmp_ln24_fu_152_p2.read();
        icmp_ln24_reg_780_pp0_iter1_reg = icmp_ln24_reg_780.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln24_reg_780_pp0_iter10_reg = icmp_ln24_reg_780_pp0_iter9_reg.read();
        icmp_ln24_reg_780_pp0_iter11_reg = icmp_ln24_reg_780_pp0_iter10_reg.read();
        icmp_ln24_reg_780_pp0_iter12_reg = icmp_ln24_reg_780_pp0_iter11_reg.read();
        icmp_ln24_reg_780_pp0_iter13_reg = icmp_ln24_reg_780_pp0_iter12_reg.read();
        icmp_ln24_reg_780_pp0_iter2_reg = icmp_ln24_reg_780_pp0_iter1_reg.read();
        icmp_ln24_reg_780_pp0_iter3_reg = icmp_ln24_reg_780_pp0_iter2_reg.read();
        icmp_ln24_reg_780_pp0_iter4_reg = icmp_ln24_reg_780_pp0_iter3_reg.read();
        icmp_ln24_reg_780_pp0_iter5_reg = icmp_ln24_reg_780_pp0_iter4_reg.read();
        icmp_ln24_reg_780_pp0_iter6_reg = icmp_ln24_reg_780_pp0_iter5_reg.read();
        icmp_ln24_reg_780_pp0_iter7_reg = icmp_ln24_reg_780_pp0_iter6_reg.read();
        icmp_ln24_reg_780_pp0_iter8_reg = icmp_ln24_reg_780_pp0_iter7_reg.read();
        icmp_ln24_reg_780_pp0_iter9_reg = icmp_ln24_reg_780_pp0_iter8_reg.read();
        icmp_ln935_1_reg_812_pp0_iter2_reg = icmp_ln935_1_reg_812.read();
        icmp_ln935_1_reg_812_pp0_iter3_reg = icmp_ln935_1_reg_812_pp0_iter2_reg.read();
        icmp_ln935_reg_789_pp0_iter2_reg = icmp_ln935_reg_789.read();
        icmp_ln935_reg_789_pp0_iter3_reg = icmp_ln935_reg_789_pp0_iter2_reg.read();
        p_Result_12_reg_794_pp0_iter2_reg = p_Result_12_reg_794.read();
        p_Result_12_reg_794_pp0_iter3_reg = p_Result_12_reg_794_pp0_iter2_reg.read();
        p_Result_15_reg_817_pp0_iter2_reg = p_Result_15_reg_817.read();
        p_Result_15_reg_817_pp0_iter3_reg = p_Result_15_reg_817_pp0_iter2_reg.read();
        tmp_V_7_reg_799_pp0_iter2_reg = tmp_V_7_reg_799.read();
        tmp_V_9_reg_822_pp0_iter2_reg = tmp_V_9_reg_822.read();
        trunc_ln943_1_reg_894_pp0_iter3_reg = trunc_ln943_1_reg_894.read();
        trunc_ln943_reg_862_pp0_iter3_reg = trunc_ln943_reg_862.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln935_1_reg_812 = icmp_ln935_1_fu_216_p2.read();
        icmp_ln935_reg_789 = icmp_ln935_fu_168_p2.read();
        p_Result_12_reg_794 = in_r_dout.read().range(15, 15);
        p_Result_15_reg_817 = in_r_dout.read().range(31, 31);
        p_Result_7_reg_830 = p_Result_7_fu_244_p4.read();
        p_Result_s_reg_807 = p_Result_s_fu_196_p4.read();
        tmp_V_7_reg_799 = tmp_V_7_fu_188_p3.read();
        tmp_V_9_reg_822 = tmp_V_9_fu_236_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter3_reg.read()))) {
        im_reg_925 = im_fu_773_p3.read();
        re_reg_919 = re_fu_718_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_1_reg_812.read()))) {
        lsb_index_1_reg_878 = lsb_index_1_fu_334_p2.read();
        sub_ln944_1_reg_867 = sub_ln944_1_fu_324_p2.read();
        sub_ln947_1_reg_889 = sub_ln947_1_fu_354_p2.read();
        tmp_11_reg_884 = lsb_index_1_fu_334_p2.read().range(31, 1);
        trunc_ln943_1_reg_894 = trunc_ln943_1_fu_360_p1.read();
        trunc_ln944_1_reg_873 = trunc_ln944_1_fu_330_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_789.read()))) {
        lsb_index_reg_846 = lsb_index_fu_279_p2.read();
        sub_ln944_reg_835 = sub_ln944_fu_269_p2.read();
        sub_ln947_reg_857 = sub_ln947_fu_299_p2.read();
        tmp_6_reg_852 = lsb_index_fu_279_p2.read().range(31, 1);
        trunc_ln943_reg_862 = trunc_ln943_fu_305_p1.read();
        trunc_ln944_reg_841 = trunc_ln944_fu_275_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_1_reg_812_pp0_iter2_reg.read()))) {
        m_3_reg_909 = m_12_fu_646_p2.read().range(63, 1);
        tmp_13_reg_914 = m_12_fu_646_p2.read().range(25, 25);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_789_pp0_iter2_reg.read()))) {
        m_s_reg_899 = m_2_fu_493_p2.read().range(63, 1);
        tmp_9_reg_904 = m_2_fu_493_p2.read().range(25, 25);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter7_reg.read()))) {
        tmp_1_reg_936 = grp_fu_148_p2.read();
        tmp_reg_931 = grp_fu_144_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter12_reg.read()))) {
        tmp_2_reg_941 = grp_fu_140_p2.read();
    }
}

void dummy_proc_be::thread_a_1_fu_542_p2() {
    a_1_fu_542_p2 = (icmp_ln947_2_fu_517_p2.read() & icmp_ln947_3_fu_536_p2.read());
}

void dummy_proc_be::thread_a_fu_389_p2() {
    a_fu_389_p2 = (icmp_ln947_fu_364_p2.read() & icmp_ln947_1_fu_383_p2.read());
}

void dummy_proc_be::thread_add_ln949_1_fu_561_p2() {
    add_ln949_1_fu_561_p2 = (!ap_const_lv16_FFE8.is_01() || !trunc_ln944_1_reg_873.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFE8) + sc_biguint<16>(trunc_ln944_1_reg_873.read()));
}

void dummy_proc_be::thread_add_ln949_fu_408_p2() {
    add_ln949_fu_408_p2 = (!ap_const_lv16_FFE8.is_01() || !trunc_ln944_reg_841.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFE8) + sc_biguint<16>(trunc_ln944_reg_841.read()));
}

void dummy_proc_be::thread_add_ln958_1_fu_604_p2() {
    add_ln958_1_fu_604_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_1_reg_867.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_1_reg_867.read()));
}

void dummy_proc_be::thread_add_ln958_fu_451_p2() {
    add_ln958_fu_451_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_reg_835.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_reg_835.read()));
}

void dummy_proc_be::thread_add_ln964_1_fu_740_p2() {
    add_ln964_1_fu_740_p2 = (!sub_ln964_1_fu_735_p2.read().is_01() || !select_ln964_1_fu_728_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln964_1_fu_735_p2.read()) + sc_biguint<8>(select_ln964_1_fu_728_p3.read()));
}

void dummy_proc_be::thread_add_ln964_fu_685_p2() {
    add_ln964_fu_685_p2 = (!sub_ln964_fu_680_p2.read().is_01() || !select_ln964_fu_673_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln964_fu_680_p2.read()) + sc_biguint<8>(select_ln964_fu_673_p3.read()));
}

void dummy_proc_be::thread_and_ln949_1_fu_573_p2() {
    and_ln949_1_fu_573_p2 = (p_Result_10_fu_566_p3.read() & xor_ln949_1_fu_555_p2.read());
}

void dummy_proc_be::thread_and_ln949_fu_420_p2() {
    and_ln949_fu_420_p2 = (p_Result_4_fu_413_p3.read() & xor_ln949_fu_402_p2.read());
}

void dummy_proc_be::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dummy_proc_be::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dummy_proc_be::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[2];
}

void dummy_proc_be::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())));
}

void dummy_proc_be::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())));
}

void dummy_proc_be::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read())));
}

void dummy_proc_be::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dummy_proc_be::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_r_full_n.read()));
}

void dummy_proc_be::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_r_empty_n.read()));
}

void dummy_proc_be::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dummy_proc_be::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln24_fu_152_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dummy_proc_be::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dummy_proc_be::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_bitcast_ln739_1_fu_769_p1() {
    bitcast_ln739_1_fu_769_p1 = trunc_ln738_1_fu_765_p1.read();
}

void dummy_proc_be::thread_bitcast_ln739_fu_714_p1() {
    bitcast_ln739_fu_714_p1 = trunc_ln738_fu_710_p1.read();
}

void dummy_proc_be::thread_grp_fu_140_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_140_ce = ap_const_logic_1;
    } else {
        grp_fu_140_ce = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_grp_fu_144_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_144_ce = ap_const_logic_1;
    } else {
        grp_fu_144_ce = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_grp_fu_148_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_148_ce = ap_const_logic_1;
    } else {
        grp_fu_148_ce = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_i_fu_158_p2() {
    i_fu_158_p2 = (!i_0_reg_129.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_129.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void dummy_proc_be::thread_icmp_ln24_fu_152_p2() {
    icmp_ln24_fu_152_p2 = (!i_0_reg_129.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_129.read() == ap_const_lv11_400);
}

void dummy_proc_be::thread_icmp_ln935_1_fu_216_p2() {
    icmp_ln935_1_fu_216_p2 = (!tmp_V_8_fu_206_p4.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_8_fu_206_p4.read() == ap_const_lv16_0);
}

void dummy_proc_be::thread_icmp_ln935_fu_168_p2() {
    icmp_ln935_fu_168_p2 = (!tmp_V_6_fu_164_p1.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_6_fu_164_p1.read() == ap_const_lv16_0);
}

void dummy_proc_be::thread_icmp_ln947_1_fu_383_p2() {
    icmp_ln947_1_fu_383_p2 = (!p_Result_3_fu_378_p2.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_3_fu_378_p2.read() != ap_const_lv16_0);
}

void dummy_proc_be::thread_icmp_ln947_2_fu_517_p2() {
    icmp_ln947_2_fu_517_p2 = (!tmp_11_reg_884.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_11_reg_884.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void dummy_proc_be::thread_icmp_ln947_3_fu_536_p2() {
    icmp_ln947_3_fu_536_p2 = (!p_Result_9_fu_531_p2.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_9_fu_531_p2.read() != ap_const_lv16_0);
}

void dummy_proc_be::thread_icmp_ln947_fu_364_p2() {
    icmp_ln947_fu_364_p2 = (!tmp_6_reg_852.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_6_reg_852.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void dummy_proc_be::thread_icmp_ln958_1_fu_599_p2() {
    icmp_ln958_1_fu_599_p2 = (!lsb_index_1_reg_878.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_1_reg_878.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dummy_proc_be::thread_icmp_ln958_fu_446_p2() {
    icmp_ln958_fu_446_p2 = (!lsb_index_reg_846.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_reg_846.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dummy_proc_be::thread_im_fu_773_p3() {
    im_fu_773_p3 = (!icmp_ln935_1_reg_812_pp0_iter3_reg.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_1_reg_812_pp0_iter3_reg.read()[0].to_bool())? ap_const_lv32_0: bitcast_ln739_1_fu_769_p1.read());
}

void dummy_proc_be::thread_in_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0))) {
        in_r_blk_n = in_r_empty_n.read();
    } else {
        in_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_in_r_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln24_reg_780.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_r_read = ap_const_logic_1;
    } else {
        in_r_read = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_l_1_fu_316_p3() {
    l_1_fu_316_p3 = esl_cttz<32,32>(p_Result_16_fu_309_p3.read());
}

void dummy_proc_be::thread_l_fu_261_p3() {
    l_fu_261_p3 = esl_cttz<32,32>(p_Result_13_fu_254_p3.read());
}

void dummy_proc_be::thread_lsb_index_1_fu_334_p2() {
    lsb_index_1_fu_334_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_1_fu_324_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_1_fu_324_p2.read()));
}

void dummy_proc_be::thread_lsb_index_fu_279_p2() {
    lsb_index_fu_279_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_fu_269_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_fu_269_p2.read()));
}

void dummy_proc_be::thread_lshr_ln947_1_fu_525_p2() {
    lshr_ln947_1_fu_525_p2 = (!zext_ln947_1_fu_522_p1.read().is_01())? sc_lv<16>(): ap_const_lv16_FFFF >> (unsigned short)zext_ln947_1_fu_522_p1.read().to_uint();
}

void dummy_proc_be::thread_lshr_ln947_fu_372_p2() {
    lshr_ln947_fu_372_p2 = (!zext_ln947_fu_369_p1.read().is_01())? sc_lv<16>(): ap_const_lv16_FFFF >> (unsigned short)zext_ln947_fu_369_p1.read().to_uint();
}

void dummy_proc_be::thread_lshr_ln958_1_fu_609_p2() {
    lshr_ln958_1_fu_609_p2 = (!add_ln958_1_fu_604_p2.read().is_01())? sc_lv<32>(): zext_ln957_2_fu_596_p1.read() >> (unsigned short)add_ln958_1_fu_604_p2.read().to_uint();
}

void dummy_proc_be::thread_lshr_ln958_fu_456_p2() {
    lshr_ln958_fu_456_p2 = (!add_ln958_fu_451_p2.read().is_01())? sc_lv<32>(): zext_ln957_1_fu_443_p1.read() >> (unsigned short)add_ln958_fu_451_p2.read().to_uint();
}

void dummy_proc_be::thread_m_10_fu_634_p3() {
    m_10_fu_634_p3 = (!icmp_ln958_1_fu_599_p2.read()[0].is_01())? sc_lv<64>(): ((icmp_ln958_1_fu_599_p2.read()[0].to_bool())? zext_ln958_2_fu_615_p1.read(): shl_ln958_1_fu_628_p2.read());
}

void dummy_proc_be::thread_m_12_fu_646_p2() {
    m_12_fu_646_p2 = (!zext_ln961_1_fu_642_p1.read().is_01() || !m_10_fu_634_p3.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln961_1_fu_642_p1.read()) + sc_biguint<64>(m_10_fu_634_p3.read()));
}

void dummy_proc_be::thread_m_15_fu_670_p1() {
    m_15_fu_670_p1 = esl_zext<64,63>(m_s_reg_899.read());
}

void dummy_proc_be::thread_m_16_fu_725_p1() {
    m_16_fu_725_p1 = esl_zext<64,63>(m_3_reg_909.read());
}

void dummy_proc_be::thread_m_1_fu_481_p3() {
    m_1_fu_481_p3 = (!icmp_ln958_fu_446_p2.read()[0].is_01())? sc_lv<64>(): ((icmp_ln958_fu_446_p2.read()[0].to_bool())? zext_ln958_fu_462_p1.read(): shl_ln958_fu_475_p2.read());
}

void dummy_proc_be::thread_m_2_fu_493_p2() {
    m_2_fu_493_p2 = (!zext_ln961_fu_489_p1.read().is_01() || !m_1_fu_481_p3.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln961_fu_489_p1.read()) + sc_biguint<64>(m_1_fu_481_p3.read()));
}

void dummy_proc_be::thread_m_9_fu_593_p1() {
    m_9_fu_593_p1 = esl_zext<64,16>(tmp_V_9_reg_822_pp0_iter2_reg.read());
}

void dummy_proc_be::thread_m_fu_440_p1() {
    m_fu_440_p1 = esl_zext<64,16>(tmp_V_7_reg_799_pp0_iter2_reg.read());
}

void dummy_proc_be::thread_or_ln949_1_fu_585_p3() {
    or_ln949_1_fu_585_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_fu_579_p2.read());
}

void dummy_proc_be::thread_or_ln949_2_fu_426_p2() {
    or_ln949_2_fu_426_p2 = (and_ln949_fu_420_p2.read() | a_fu_389_p2.read());
}

void dummy_proc_be::thread_or_ln949_fu_579_p2() {
    or_ln949_fu_579_p2 = (and_ln949_1_fu_573_p2.read() | a_1_fu_542_p2.read());
}

void dummy_proc_be::thread_or_ln_fu_432_p3() {
    or_ln_fu_432_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_2_fu_426_p2.read());
}

void dummy_proc_be::thread_out_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()))) {
        out_r_blk_n = out_r_full_n.read();
    } else {
        out_r_blk_n = ap_const_logic_1;
    }
}

void dummy_proc_be::thread_out_r_din() {
    out_r_din = tmp_2_reg_941.read();
}

void dummy_proc_be::thread_out_r_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_reg_780_pp0_iter13_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_r_write = ap_const_logic_1;
    } else {
        out_r_write = ap_const_logic_0;
    }
}

void dummy_proc_be::thread_p_Result_10_fu_566_p3() {
    p_Result_10_fu_566_p3 = (!add_ln949_1_fu_561_p2.read().is_01() || sc_biguint<16>(add_ln949_1_fu_561_p2.read()).to_uint() >= 16)? sc_lv<1>(): tmp_V_9_reg_822_pp0_iter2_reg.read().range(sc_biguint<16>(add_ln949_1_fu_561_p2.read()).to_uint(), sc_biguint<16>(add_ln949_1_fu_561_p2.read()).to_uint());
}

void dummy_proc_be::thread_p_Result_12_fu_174_p3() {
    p_Result_12_fu_174_p3 = in_r_dout.read().range(15, 15);
}

void dummy_proc_be::thread_p_Result_13_fu_254_p3() {
    p_Result_13_fu_254_p3 = esl_concat<16,16>(ap_const_lv16_FFFF, p_Result_s_reg_807.read());
}

void dummy_proc_be::thread_p_Result_14_fu_698_p5() {
    p_Result_14_fu_698_p5 = esl_partset<64,64,9,32,32>(m_15_fu_670_p1.read(), tmp_5_fu_691_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void dummy_proc_be::thread_p_Result_15_fu_222_p3() {
    p_Result_15_fu_222_p3 = in_r_dout.read().range(31, 31);
}

void dummy_proc_be::thread_p_Result_16_fu_309_p3() {
    p_Result_16_fu_309_p3 = esl_concat<16,16>(ap_const_lv16_FFFF, p_Result_7_reg_830.read());
}

void dummy_proc_be::thread_p_Result_17_fu_753_p5() {
    p_Result_17_fu_753_p5 = esl_partset<64,64,9,32,32>(m_16_fu_725_p1.read(), tmp_7_fu_746_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void dummy_proc_be::thread_p_Result_3_fu_378_p2() {
    p_Result_3_fu_378_p2 = (tmp_V_7_reg_799_pp0_iter2_reg.read() & lshr_ln947_fu_372_p2.read());
}

void dummy_proc_be::thread_p_Result_4_fu_413_p3() {
    p_Result_4_fu_413_p3 = (!add_ln949_fu_408_p2.read().is_01() || sc_biguint<16>(add_ln949_fu_408_p2.read()).to_uint() >= 16)? sc_lv<1>(): tmp_V_7_reg_799_pp0_iter2_reg.read().range(sc_biguint<16>(add_ln949_fu_408_p2.read()).to_uint(), sc_biguint<16>(add_ln949_fu_408_p2.read()).to_uint());
}

void dummy_proc_be::thread_p_Result_7_fu_244_p4() {
    p_Result_7_fu_244_p4 = tmp_V_9_fu_236_p3.read().range(0, 15);
}

void dummy_proc_be::thread_p_Result_9_fu_531_p2() {
    p_Result_9_fu_531_p2 = (tmp_V_9_reg_822_pp0_iter2_reg.read() & lshr_ln947_1_fu_525_p2.read());
}

void dummy_proc_be::thread_p_Result_s_fu_196_p4() {
    p_Result_s_fu_196_p4 = tmp_V_7_fu_188_p3.read().range(0, 15);
}

void dummy_proc_be::thread_re_fu_718_p3() {
    re_fu_718_p3 = (!icmp_ln935_reg_789_pp0_iter3_reg.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_reg_789_pp0_iter3_reg.read()[0].to_bool())? ap_const_lv32_0: bitcast_ln739_fu_714_p1.read());
}

void dummy_proc_be::thread_select_ln964_1_fu_728_p3() {
    select_ln964_1_fu_728_p3 = (!tmp_13_reg_914.read()[0].is_01())? sc_lv<8>(): ((tmp_13_reg_914.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void dummy_proc_be::thread_select_ln964_fu_673_p3() {
    select_ln964_fu_673_p3 = (!tmp_9_reg_904.read()[0].is_01())? sc_lv<8>(): ((tmp_9_reg_904.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void dummy_proc_be::thread_shl_ln958_1_fu_628_p2() {
    shl_ln958_1_fu_628_p2 = (!zext_ln958_3_fu_624_p1.read().is_01())? sc_lv<64>(): m_9_fu_593_p1.read() << (unsigned short)zext_ln958_3_fu_624_p1.read().to_uint();
}

void dummy_proc_be::thread_shl_ln958_fu_475_p2() {
    shl_ln958_fu_475_p2 = (!zext_ln958_1_fu_471_p1.read().is_01())? sc_lv<64>(): m_fu_440_p1.read() << (unsigned short)zext_ln958_1_fu_471_p1.read().to_uint();
}

void dummy_proc_be::thread_sub_ln944_1_fu_324_p2() {
    sub_ln944_1_fu_324_p2 = (!ap_const_lv32_10.is_01() || !l_1_fu_316_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_10) - sc_biguint<32>(l_1_fu_316_p3.read()));
}

void dummy_proc_be::thread_sub_ln944_fu_269_p2() {
    sub_ln944_fu_269_p2 = (!ap_const_lv32_10.is_01() || !l_fu_261_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_10) - sc_biguint<32>(l_fu_261_p3.read()));
}

void dummy_proc_be::thread_sub_ln947_1_fu_354_p2() {
    sub_ln947_1_fu_354_p2 = (!ap_const_lv5_9.is_01() || !trunc_ln947_1_fu_350_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_9) - sc_biguint<5>(trunc_ln947_1_fu_350_p1.read()));
}

void dummy_proc_be::thread_sub_ln947_fu_299_p2() {
    sub_ln947_fu_299_p2 = (!ap_const_lv5_9.is_01() || !trunc_ln947_fu_295_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_9) - sc_biguint<5>(trunc_ln947_fu_295_p1.read()));
}

void dummy_proc_be::thread_sub_ln958_1_fu_619_p2() {
    sub_ln958_1_fu_619_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_1_reg_867.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_1_reg_867.read()));
}

void dummy_proc_be::thread_sub_ln958_fu_466_p2() {
    sub_ln958_fu_466_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_reg_835.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_reg_835.read()));
}

void dummy_proc_be::thread_sub_ln964_1_fu_735_p2() {
    sub_ln964_1_fu_735_p2 = (!ap_const_lv8_1.is_01() || !trunc_ln943_1_reg_894_pp0_iter3_reg.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) - sc_biguint<8>(trunc_ln943_1_reg_894_pp0_iter3_reg.read()));
}

void dummy_proc_be::thread_sub_ln964_fu_680_p2() {
    sub_ln964_fu_680_p2 = (!ap_const_lv8_1.is_01() || !trunc_ln943_reg_862_pp0_iter3_reg.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) - sc_biguint<8>(trunc_ln943_reg_862_pp0_iter3_reg.read()));
}

void dummy_proc_be::thread_tmp_12_fu_548_p3() {
    tmp_12_fu_548_p3 = lsb_index_1_reg_878.read().range(31, 31);
}

void dummy_proc_be::thread_tmp_5_fu_691_p3() {
    tmp_5_fu_691_p3 = esl_concat<1,8>(p_Result_12_reg_794_pp0_iter3_reg.read(), add_ln964_fu_685_p2.read());
}

void dummy_proc_be::thread_tmp_7_fu_746_p3() {
    tmp_7_fu_746_p3 = esl_concat<1,8>(p_Result_15_reg_817_pp0_iter3_reg.read(), add_ln964_1_fu_740_p2.read());
}

void dummy_proc_be::thread_tmp_8_fu_395_p3() {
    tmp_8_fu_395_p3 = lsb_index_reg_846.read().range(31, 31);
}

void dummy_proc_be::thread_tmp_V_4_fu_230_p2() {
    tmp_V_4_fu_230_p2 = (!ap_const_lv16_0.is_01() || !tmp_V_8_fu_206_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(tmp_V_8_fu_206_p4.read()));
}

void dummy_proc_be::thread_tmp_V_6_fu_164_p1() {
    tmp_V_6_fu_164_p1 = in_r_dout.read().range(16-1, 0);
}

void dummy_proc_be::thread_tmp_V_7_fu_188_p3() {
    tmp_V_7_fu_188_p3 = (!p_Result_12_fu_174_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_12_fu_174_p3.read()[0].to_bool())? tmp_V_fu_182_p2.read(): tmp_V_6_fu_164_p1.read());
}

void dummy_proc_be::thread_tmp_V_8_fu_206_p4() {
    tmp_V_8_fu_206_p4 = in_r_dout.read().range(31, 16);
}

void dummy_proc_be::thread_tmp_V_9_fu_236_p3() {
    tmp_V_9_fu_236_p3 = (!p_Result_15_fu_222_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_15_fu_222_p3.read()[0].to_bool())? tmp_V_4_fu_230_p2.read(): tmp_V_8_fu_206_p4.read());
}

void dummy_proc_be::thread_tmp_V_fu_182_p2() {
    tmp_V_fu_182_p2 = (!ap_const_lv16_0.is_01() || !tmp_V_6_fu_164_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(tmp_V_6_fu_164_p1.read()));
}

void dummy_proc_be::thread_trunc_ln738_1_fu_765_p1() {
    trunc_ln738_1_fu_765_p1 = p_Result_17_fu_753_p5.read().range(32-1, 0);
}

void dummy_proc_be::thread_trunc_ln738_fu_710_p1() {
    trunc_ln738_fu_710_p1 = p_Result_14_fu_698_p5.read().range(32-1, 0);
}

void dummy_proc_be::thread_trunc_ln943_1_fu_360_p1() {
    trunc_ln943_1_fu_360_p1 = l_1_fu_316_p3.read().range(8-1, 0);
}

void dummy_proc_be::thread_trunc_ln943_fu_305_p1() {
    trunc_ln943_fu_305_p1 = l_fu_261_p3.read().range(8-1, 0);
}

void dummy_proc_be::thread_trunc_ln944_1_fu_330_p1() {
    trunc_ln944_1_fu_330_p1 = sub_ln944_1_fu_324_p2.read().range(16-1, 0);
}

void dummy_proc_be::thread_trunc_ln944_fu_275_p1() {
    trunc_ln944_fu_275_p1 = sub_ln944_fu_269_p2.read().range(16-1, 0);
}

void dummy_proc_be::thread_trunc_ln947_1_fu_350_p1() {
    trunc_ln947_1_fu_350_p1 = sub_ln944_1_fu_324_p2.read().range(5-1, 0);
}

void dummy_proc_be::thread_trunc_ln947_fu_295_p1() {
    trunc_ln947_fu_295_p1 = sub_ln944_fu_269_p2.read().range(5-1, 0);
}

void dummy_proc_be::thread_xor_ln949_1_fu_555_p2() {
    xor_ln949_1_fu_555_p2 = (tmp_12_fu_548_p3.read() ^ ap_const_lv1_1);
}

void dummy_proc_be::thread_xor_ln949_fu_402_p2() {
    xor_ln949_fu_402_p2 = (tmp_8_fu_395_p3.read() ^ ap_const_lv1_1);
}

void dummy_proc_be::thread_zext_ln947_1_fu_522_p1() {
    zext_ln947_1_fu_522_p1 = esl_zext<16,5>(sub_ln947_1_reg_889.read());
}

void dummy_proc_be::thread_zext_ln947_fu_369_p1() {
    zext_ln947_fu_369_p1 = esl_zext<16,5>(sub_ln947_reg_857.read());
}

void dummy_proc_be::thread_zext_ln957_1_fu_443_p1() {
    zext_ln957_1_fu_443_p1 = esl_zext<32,16>(tmp_V_7_reg_799_pp0_iter2_reg.read());
}

void dummy_proc_be::thread_zext_ln957_2_fu_596_p1() {
    zext_ln957_2_fu_596_p1 = esl_zext<32,16>(tmp_V_9_reg_822_pp0_iter2_reg.read());
}

void dummy_proc_be::thread_zext_ln958_1_fu_471_p1() {
    zext_ln958_1_fu_471_p1 = esl_zext<64,32>(sub_ln958_fu_466_p2.read());
}

void dummy_proc_be::thread_zext_ln958_2_fu_615_p1() {
    zext_ln958_2_fu_615_p1 = esl_zext<64,32>(lshr_ln958_1_fu_609_p2.read());
}

void dummy_proc_be::thread_zext_ln958_3_fu_624_p1() {
    zext_ln958_3_fu_624_p1 = esl_zext<64,32>(sub_ln958_1_fu_619_p2.read());
}

void dummy_proc_be::thread_zext_ln958_fu_462_p1() {
    zext_ln958_fu_462_p1 = esl_zext<64,32>(lshr_ln958_fu_456_p2.read());
}

void dummy_proc_be::thread_zext_ln961_1_fu_642_p1() {
    zext_ln961_1_fu_642_p1 = esl_zext<64,32>(or_ln949_1_fu_585_p3.read());
}

void dummy_proc_be::thread_zext_ln961_fu_489_p1() {
    zext_ln961_fu_489_p1 = esl_zext<64,32>(or_ln_fu_432_p3.read());
}

void dummy_proc_be::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter13.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln24_fu_152_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter14.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter13.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln24_fu_152_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

