-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dummy_proc_be is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_r_empty_n : IN STD_LOGIC;
    in_r_read : OUT STD_LOGIC;
    out_r_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_full_n : IN STD_LOGIC;
    out_r_write : OUT STD_LOGIC );
end;


architecture behav of dummy_proc_be is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv16_FFE8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101000";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_r_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln24_reg_780 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal icmp_ln24_reg_780_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_reg_129 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln24_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln24_reg_780_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_780_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_158_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln935_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_reg_789 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_reg_789_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_reg_789_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_reg_794 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_reg_794_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_reg_794_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_7_fu_188_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_7_reg_799 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_7_reg_799_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_196_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_reg_807 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln935_1_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_1_reg_812 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_1_reg_812_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_1_reg_812_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_reg_817 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_reg_817_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_15_reg_817_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_9_fu_236_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_9_reg_822 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_9_reg_822_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_7_fu_244_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_7_reg_830 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln944_fu_269_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln944_reg_835 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln944_fu_275_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln944_reg_841 : STD_LOGIC_VECTOR (15 downto 0);
    signal lsb_index_fu_279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsb_index_reg_846 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_reg_852 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_ln947_fu_299_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln947_reg_857 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln943_fu_305_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln943_reg_862 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln943_reg_862_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln944_1_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln944_1_reg_867 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln944_1_fu_330_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln944_1_reg_873 : STD_LOGIC_VECTOR (15 downto 0);
    signal lsb_index_1_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsb_index_1_reg_878 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_reg_884 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_ln947_1_fu_354_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln947_1_reg_889 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln943_1_fu_360_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln943_1_reg_894 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln943_1_reg_894_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m_s_reg_899 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_9_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_3_reg_909 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_13_reg_914 : STD_LOGIC_VECTOR (0 downto 0);
    signal re_fu_718_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal re_reg_919 : STD_LOGIC_VECTOR (31 downto 0);
    signal im_fu_773_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal im_reg_925 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_931 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_936 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_941 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_V_6_fu_164_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_fu_182_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_8_fu_206_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_4_fu_230_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_13_fu_254_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_fu_261_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln947_fu_295_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_16_fu_309_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_1_fu_316_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln947_1_fu_350_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln947_fu_369_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln947_fu_372_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_3_fu_378_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln947_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln947_1_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_395_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln949_fu_408_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_4_fu_413_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln949_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln949_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln949_2_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln957_1_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln958_fu_451_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln958_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln958_fu_466_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_fu_440_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln958_1_fu_471_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln958_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln958_fu_462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln958_fu_475_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln_fu_432_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln961_fu_489_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_1_fu_481_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_2_fu_493_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln947_1_fu_522_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln947_1_fu_525_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_9_fu_531_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln947_2_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln947_3_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln949_1_fu_561_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_10_fu_566_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln949_1_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln949_1_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_1_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln949_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln957_2_fu_596_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln958_1_fu_604_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln958_1_fu_609_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln958_1_fu_619_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_9_fu_593_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln958_3_fu_624_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln958_1_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln958_2_fu_615_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln958_1_fu_628_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln949_1_fu_585_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln961_1_fu_642_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_10_fu_634_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_12_fu_646_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln964_fu_680_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln964_fu_673_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln964_fu_685_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_15_fu_670_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_fu_691_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_14_fu_698_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln738_fu_710_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln739_fu_714_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln964_1_fu_735_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln964_1_fu_728_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln964_1_fu_740_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_16_fu_725_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_7_fu_746_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_17_fu_753_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln738_1_fu_765_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln739_1_fu_769_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_ce : STD_LOGIC;
    signal grp_fu_144_ce : STD_LOGIC;
    signal grp_fu_148_ce : STD_LOGIC;
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component fft_top_fadd_32nsbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_top_fmul_32nscud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    fft_top_fadd_32nsbkb_U4 : component fft_top_fadd_32nsbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_reg_931,
        din1 => tmp_1_reg_936,
        ce => grp_fu_140_ce,
        dout => grp_fu_140_p2);

    fft_top_fmul_32nscud_U5 : component fft_top_fmul_32nscud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => re_reg_919,
        din1 => re_reg_919,
        ce => grp_fu_144_ce,
        dout => grp_fu_144_p2);

    fft_top_fmul_32nscud_U6 : component fft_top_fmul_32nscud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => im_reg_925,
        din1 => im_reg_925,
        ce => grp_fu_148_ce,
        dout => grp_fu_148_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_0_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                i_0_reg_129 <= i_fu_158_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_129 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln24_reg_780 <= icmp_ln24_fu_152_p2;
                icmp_ln24_reg_780_pp0_iter1_reg <= icmp_ln24_reg_780;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln24_reg_780_pp0_iter10_reg <= icmp_ln24_reg_780_pp0_iter9_reg;
                icmp_ln24_reg_780_pp0_iter11_reg <= icmp_ln24_reg_780_pp0_iter10_reg;
                icmp_ln24_reg_780_pp0_iter12_reg <= icmp_ln24_reg_780_pp0_iter11_reg;
                icmp_ln24_reg_780_pp0_iter13_reg <= icmp_ln24_reg_780_pp0_iter12_reg;
                icmp_ln24_reg_780_pp0_iter2_reg <= icmp_ln24_reg_780_pp0_iter1_reg;
                icmp_ln24_reg_780_pp0_iter3_reg <= icmp_ln24_reg_780_pp0_iter2_reg;
                icmp_ln24_reg_780_pp0_iter4_reg <= icmp_ln24_reg_780_pp0_iter3_reg;
                icmp_ln24_reg_780_pp0_iter5_reg <= icmp_ln24_reg_780_pp0_iter4_reg;
                icmp_ln24_reg_780_pp0_iter6_reg <= icmp_ln24_reg_780_pp0_iter5_reg;
                icmp_ln24_reg_780_pp0_iter7_reg <= icmp_ln24_reg_780_pp0_iter6_reg;
                icmp_ln24_reg_780_pp0_iter8_reg <= icmp_ln24_reg_780_pp0_iter7_reg;
                icmp_ln24_reg_780_pp0_iter9_reg <= icmp_ln24_reg_780_pp0_iter8_reg;
                icmp_ln935_1_reg_812_pp0_iter2_reg <= icmp_ln935_1_reg_812;
                icmp_ln935_1_reg_812_pp0_iter3_reg <= icmp_ln935_1_reg_812_pp0_iter2_reg;
                icmp_ln935_reg_789_pp0_iter2_reg <= icmp_ln935_reg_789;
                icmp_ln935_reg_789_pp0_iter3_reg <= icmp_ln935_reg_789_pp0_iter2_reg;
                p_Result_12_reg_794_pp0_iter2_reg <= p_Result_12_reg_794;
                p_Result_12_reg_794_pp0_iter3_reg <= p_Result_12_reg_794_pp0_iter2_reg;
                p_Result_15_reg_817_pp0_iter2_reg <= p_Result_15_reg_817;
                p_Result_15_reg_817_pp0_iter3_reg <= p_Result_15_reg_817_pp0_iter2_reg;
                tmp_V_7_reg_799_pp0_iter2_reg <= tmp_V_7_reg_799;
                tmp_V_9_reg_822_pp0_iter2_reg <= tmp_V_9_reg_822;
                trunc_ln943_1_reg_894_pp0_iter3_reg <= trunc_ln943_1_reg_894;
                trunc_ln943_reg_862_pp0_iter3_reg <= trunc_ln943_reg_862;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln935_1_reg_812 <= icmp_ln935_1_fu_216_p2;
                icmp_ln935_reg_789 <= icmp_ln935_fu_168_p2;
                p_Result_12_reg_794 <= in_r_dout(15 downto 15);
                p_Result_15_reg_817 <= in_r_dout(31 downto 31);
                p_Result_7_reg_830 <= p_Result_7_fu_244_p4;
                p_Result_s_reg_807 <= p_Result_s_fu_196_p4;
                tmp_V_7_reg_799 <= tmp_V_7_fu_188_p3;
                tmp_V_9_reg_822 <= tmp_V_9_fu_236_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter3_reg = ap_const_lv1_0))) then
                im_reg_925 <= im_fu_773_p3;
                re_reg_919 <= re_fu_718_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln935_1_reg_812 = ap_const_lv1_0))) then
                lsb_index_1_reg_878 <= lsb_index_1_fu_334_p2;
                sub_ln944_1_reg_867 <= sub_ln944_1_fu_324_p2;
                sub_ln947_1_reg_889 <= sub_ln947_1_fu_354_p2;
                tmp_11_reg_884 <= lsb_index_1_fu_334_p2(31 downto 1);
                trunc_ln943_1_reg_894 <= trunc_ln943_1_fu_360_p1;
                trunc_ln944_1_reg_873 <= trunc_ln944_1_fu_330_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln935_reg_789 = ap_const_lv1_0))) then
                lsb_index_reg_846 <= lsb_index_fu_279_p2;
                sub_ln944_reg_835 <= sub_ln944_fu_269_p2;
                sub_ln947_reg_857 <= sub_ln947_fu_299_p2;
                tmp_6_reg_852 <= lsb_index_fu_279_p2(31 downto 1);
                trunc_ln943_reg_862 <= trunc_ln943_fu_305_p1;
                trunc_ln944_reg_841 <= trunc_ln944_fu_275_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln935_1_reg_812_pp0_iter2_reg = ap_const_lv1_0))) then
                m_3_reg_909 <= m_12_fu_646_p2(63 downto 1);
                tmp_13_reg_914 <= m_12_fu_646_p2(25 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln935_reg_789_pp0_iter2_reg = ap_const_lv1_0))) then
                m_s_reg_899 <= m_2_fu_493_p2(63 downto 1);
                tmp_9_reg_904 <= m_2_fu_493_p2(25 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter7_reg = ap_const_lv1_0))) then
                tmp_1_reg_936 <= grp_fu_148_p2;
                tmp_reg_931 <= grp_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter12_reg = ap_const_lv1_0))) then
                tmp_2_reg_941 <= grp_fu_140_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter14, icmp_ln24_fu_152_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter13)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln24_fu_152_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1)) or ((icmp_ln24_fu_152_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    a_1_fu_542_p2 <= (icmp_ln947_3_fu_536_p2 and icmp_ln947_2_fu_517_p2);
    a_fu_389_p2 <= (icmp_ln947_fu_364_p2 and icmp_ln947_1_fu_383_p2);
    add_ln949_1_fu_561_p2 <= std_logic_vector(signed(ap_const_lv16_FFE8) + signed(trunc_ln944_1_reg_873));
    add_ln949_fu_408_p2 <= std_logic_vector(signed(ap_const_lv16_FFE8) + signed(trunc_ln944_reg_841));
    add_ln958_1_fu_604_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE7) + signed(sub_ln944_1_reg_867));
    add_ln958_fu_451_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE7) + signed(sub_ln944_reg_835));
    add_ln964_1_fu_740_p2 <= std_logic_vector(unsigned(sub_ln964_1_fu_735_p2) + unsigned(select_ln964_1_fu_728_p3));
    add_ln964_fu_685_p2 <= std_logic_vector(unsigned(sub_ln964_fu_680_p2) + unsigned(select_ln964_fu_673_p3));
    and_ln949_1_fu_573_p2 <= (xor_ln949_1_fu_555_p2 and p_Result_10_fu_566_p3);
    and_ln949_fu_420_p2 <= (xor_ln949_fu_402_p2 and p_Result_4_fu_413_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state17 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_r_empty_n, out_r_full_n, ap_enable_reg_pp0_iter1, icmp_ln24_reg_780, ap_enable_reg_pp0_iter14, icmp_ln24_reg_780_pp0_iter13_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (out_r_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1)) or ((icmp_ln24_reg_780 = ap_const_lv1_0) and (in_r_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_r_empty_n, out_r_full_n, ap_enable_reg_pp0_iter1, icmp_ln24_reg_780, ap_enable_reg_pp0_iter14, icmp_ln24_reg_780_pp0_iter13_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (out_r_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1)) or ((icmp_ln24_reg_780 = ap_const_lv1_0) and (in_r_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_r_empty_n, out_r_full_n, ap_enable_reg_pp0_iter1, icmp_ln24_reg_780, ap_enable_reg_pp0_iter14, icmp_ln24_reg_780_pp0_iter13_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (out_r_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1)) or ((icmp_ln24_reg_780 = ap_const_lv1_0) and (in_r_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state16_pp0_stage0_iter14_assign_proc : process(out_r_full_n, icmp_ln24_reg_780_pp0_iter13_reg)
    begin
                ap_block_state16_pp0_stage0_iter14 <= ((icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (out_r_full_n = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(in_r_empty_n, icmp_ln24_reg_780)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln24_reg_780 = ap_const_lv1_0) and (in_r_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln24_fu_152_p2)
    begin
        if ((icmp_ln24_fu_152_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln739_1_fu_769_p1 <= trunc_ln738_1_fu_765_p1;
    bitcast_ln739_fu_714_p1 <= trunc_ln738_fu_710_p1;

    grp_fu_140_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_140_ce <= ap_const_logic_1;
        else 
            grp_fu_140_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_144_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_144_ce <= ap_const_logic_1;
        else 
            grp_fu_144_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_148_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_148_ce <= ap_const_logic_1;
        else 
            grp_fu_148_ce <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_158_p2 <= std_logic_vector(unsigned(i_0_reg_129) + unsigned(ap_const_lv11_1));
    icmp_ln24_fu_152_p2 <= "1" when (i_0_reg_129 = ap_const_lv11_400) else "0";
    icmp_ln935_1_fu_216_p2 <= "1" when (tmp_V_8_fu_206_p4 = ap_const_lv16_0) else "0";
    icmp_ln935_fu_168_p2 <= "1" when (tmp_V_6_fu_164_p1 = ap_const_lv16_0) else "0";
    icmp_ln947_1_fu_383_p2 <= "0" when (p_Result_3_fu_378_p2 = ap_const_lv16_0) else "1";
    icmp_ln947_2_fu_517_p2 <= "1" when (signed(tmp_11_reg_884) > signed(ap_const_lv31_0)) else "0";
    icmp_ln947_3_fu_536_p2 <= "0" when (p_Result_9_fu_531_p2 = ap_const_lv16_0) else "1";
    icmp_ln947_fu_364_p2 <= "1" when (signed(tmp_6_reg_852) > signed(ap_const_lv31_0)) else "0";
    icmp_ln958_1_fu_599_p2 <= "1" when (signed(lsb_index_1_reg_878) > signed(ap_const_lv32_0)) else "0";
    icmp_ln958_fu_446_p2 <= "1" when (signed(lsb_index_reg_846) > signed(ap_const_lv32_0)) else "0";
    im_fu_773_p3 <= 
        ap_const_lv32_0 when (icmp_ln935_1_reg_812_pp0_iter3_reg(0) = '1') else 
        bitcast_ln739_1_fu_769_p1;

    in_r_blk_n_assign_proc : process(in_r_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln24_reg_780)
    begin
        if (((icmp_ln24_reg_780 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_blk_n <= in_r_empty_n;
        else 
            in_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_r_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln24_reg_780, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_r_read <= ap_const_logic_1;
        else 
            in_r_read <= ap_const_logic_0;
        end if; 
    end process;

    
    l_1_fu_316_p3_proc : process(p_Result_16_fu_309_p3)
    begin
        l_1_fu_316_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_16_fu_309_p3(i) = '1' then
                l_1_fu_316_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    
    l_fu_261_p3_proc : process(p_Result_13_fu_254_p3)
    begin
        l_fu_261_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_13_fu_254_p3(i) = '1' then
                l_fu_261_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    lsb_index_1_fu_334_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE8) + signed(sub_ln944_1_fu_324_p2));
    lsb_index_fu_279_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE8) + signed(sub_ln944_fu_269_p2));
    lshr_ln947_1_fu_525_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv16_FFFF),to_integer(unsigned('0' & zext_ln947_1_fu_522_p1(16-1 downto 0)))));
    lshr_ln947_fu_372_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv16_FFFF),to_integer(unsigned('0' & zext_ln947_fu_369_p1(16-1 downto 0)))));
    lshr_ln958_1_fu_609_p2 <= std_logic_vector(shift_right(unsigned(zext_ln957_2_fu_596_p1),to_integer(unsigned('0' & add_ln958_1_fu_604_p2(31-1 downto 0)))));
    lshr_ln958_fu_456_p2 <= std_logic_vector(shift_right(unsigned(zext_ln957_1_fu_443_p1),to_integer(unsigned('0' & add_ln958_fu_451_p2(31-1 downto 0)))));
    m_10_fu_634_p3 <= 
        zext_ln958_2_fu_615_p1 when (icmp_ln958_1_fu_599_p2(0) = '1') else 
        shl_ln958_1_fu_628_p2;
    m_12_fu_646_p2 <= std_logic_vector(unsigned(zext_ln961_1_fu_642_p1) + unsigned(m_10_fu_634_p3));
    m_15_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_s_reg_899),64));
    m_16_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_3_reg_909),64));
    m_1_fu_481_p3 <= 
        zext_ln958_fu_462_p1 when (icmp_ln958_fu_446_p2(0) = '1') else 
        shl_ln958_fu_475_p2;
    m_2_fu_493_p2 <= std_logic_vector(unsigned(zext_ln961_fu_489_p1) + unsigned(m_1_fu_481_p3));
    m_9_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_9_reg_822_pp0_iter2_reg),64));
    m_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_7_reg_799_pp0_iter2_reg),64));
    or_ln949_1_fu_585_p3 <= (ap_const_lv31_0 & or_ln949_fu_579_p2);
    or_ln949_2_fu_426_p2 <= (and_ln949_fu_420_p2 or a_fu_389_p2);
    or_ln949_fu_579_p2 <= (and_ln949_1_fu_573_p2 or a_1_fu_542_p2);
    or_ln_fu_432_p3 <= (ap_const_lv31_0 & or_ln949_2_fu_426_p2);

    out_r_blk_n_assign_proc : process(out_r_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter14, icmp_ln24_reg_780_pp0_iter13_reg)
    begin
        if (((icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            out_r_blk_n <= out_r_full_n;
        else 
            out_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_din <= tmp_2_reg_941;

    out_r_write_assign_proc : process(ap_enable_reg_pp0_iter14, icmp_ln24_reg_780_pp0_iter13_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln24_reg_780_pp0_iter13_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            out_r_write <= ap_const_logic_1;
        else 
            out_r_write <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_10_fu_566_p3 <= tmp_V_9_reg_822_pp0_iter2_reg(to_integer(unsigned(add_ln949_1_fu_561_p2)) downto to_integer(unsigned(add_ln949_1_fu_561_p2))) when (to_integer(unsigned(add_ln949_1_fu_561_p2))>= 0 and to_integer(unsigned(add_ln949_1_fu_561_p2))<=15) else "-";
    p_Result_12_fu_174_p3 <= in_r_dout(15 downto 15);
    p_Result_13_fu_254_p3 <= (ap_const_lv16_FFFF & p_Result_s_reg_807);
    p_Result_14_fu_698_p5 <= (m_15_fu_670_p1(63 downto 32) & tmp_5_fu_691_p3 & m_15_fu_670_p1(22 downto 0));
    p_Result_15_fu_222_p3 <= in_r_dout(31 downto 31);
    p_Result_16_fu_309_p3 <= (ap_const_lv16_FFFF & p_Result_7_reg_830);
    p_Result_17_fu_753_p5 <= (m_16_fu_725_p1(63 downto 32) & tmp_7_fu_746_p3 & m_16_fu_725_p1(22 downto 0));
    p_Result_3_fu_378_p2 <= (tmp_V_7_reg_799_pp0_iter2_reg and lshr_ln947_fu_372_p2);
    p_Result_4_fu_413_p3 <= tmp_V_7_reg_799_pp0_iter2_reg(to_integer(unsigned(add_ln949_fu_408_p2)) downto to_integer(unsigned(add_ln949_fu_408_p2))) when (to_integer(unsigned(add_ln949_fu_408_p2))>= 0 and to_integer(unsigned(add_ln949_fu_408_p2))<=15) else "-";
    
    p_Result_7_fu_244_p4_proc : process(tmp_V_9_fu_236_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable p_Result_7_fu_244_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_F(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := tmp_V_9_fu_236_p3;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_F(4-1 downto 0)));
            for p_Result_7_fu_244_p4_i in 0 to 16-1 loop
                v0_cpy(p_Result_7_fu_244_p4_i) := tmp_V_9_fu_236_p3(16-1-p_Result_7_fu_244_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(16-1 downto 0)))));
        res_mask := res_mask(16-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_7_fu_244_p4 <= resvalue(16-1 downto 0);
    end process;

    p_Result_9_fu_531_p2 <= (tmp_V_9_reg_822_pp0_iter2_reg and lshr_ln947_1_fu_525_p2);
    
    p_Result_s_fu_196_p4_proc : process(tmp_V_7_fu_188_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable p_Result_s_fu_196_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_F(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := tmp_V_7_fu_188_p3;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_F(4-1 downto 0)));
            for p_Result_s_fu_196_p4_i in 0 to 16-1 loop
                v0_cpy(p_Result_s_fu_196_p4_i) := tmp_V_7_fu_188_p3(16-1-p_Result_s_fu_196_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(16-1 downto 0)))));
        res_mask := res_mask(16-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_s_fu_196_p4 <= resvalue(16-1 downto 0);
    end process;

    re_fu_718_p3 <= 
        ap_const_lv32_0 when (icmp_ln935_reg_789_pp0_iter3_reg(0) = '1') else 
        bitcast_ln739_fu_714_p1;
    select_ln964_1_fu_728_p3 <= 
        ap_const_lv8_7F when (tmp_13_reg_914(0) = '1') else 
        ap_const_lv8_7E;
    select_ln964_fu_673_p3 <= 
        ap_const_lv8_7F when (tmp_9_reg_904(0) = '1') else 
        ap_const_lv8_7E;
    shl_ln958_1_fu_628_p2 <= std_logic_vector(shift_left(unsigned(m_9_fu_593_p1),to_integer(unsigned('0' & zext_ln958_3_fu_624_p1(31-1 downto 0)))));
    shl_ln958_fu_475_p2 <= std_logic_vector(shift_left(unsigned(m_fu_440_p1),to_integer(unsigned('0' & zext_ln958_1_fu_471_p1(31-1 downto 0)))));
    sub_ln944_1_fu_324_p2 <= std_logic_vector(unsigned(ap_const_lv32_10) - unsigned(l_1_fu_316_p3));
    sub_ln944_fu_269_p2 <= std_logic_vector(unsigned(ap_const_lv32_10) - unsigned(l_fu_261_p3));
    sub_ln947_1_fu_354_p2 <= std_logic_vector(unsigned(ap_const_lv5_9) - unsigned(trunc_ln947_1_fu_350_p1));
    sub_ln947_fu_299_p2 <= std_logic_vector(unsigned(ap_const_lv5_9) - unsigned(trunc_ln947_fu_295_p1));
    sub_ln958_1_fu_619_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln944_1_reg_867));
    sub_ln958_fu_466_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln944_reg_835));
    sub_ln964_1_fu_735_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) - unsigned(trunc_ln943_1_reg_894_pp0_iter3_reg));
    sub_ln964_fu_680_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) - unsigned(trunc_ln943_reg_862_pp0_iter3_reg));
    tmp_12_fu_548_p3 <= lsb_index_1_reg_878(31 downto 31);
    tmp_5_fu_691_p3 <= (p_Result_12_reg_794_pp0_iter3_reg & add_ln964_fu_685_p2);
    tmp_7_fu_746_p3 <= (p_Result_15_reg_817_pp0_iter3_reg & add_ln964_1_fu_740_p2);
    tmp_8_fu_395_p3 <= lsb_index_reg_846(31 downto 31);
    tmp_V_4_fu_230_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_V_8_fu_206_p4));
    tmp_V_6_fu_164_p1 <= in_r_dout(16 - 1 downto 0);
    tmp_V_7_fu_188_p3 <= 
        tmp_V_fu_182_p2 when (p_Result_12_fu_174_p3(0) = '1') else 
        tmp_V_6_fu_164_p1;
    tmp_V_8_fu_206_p4 <= in_r_dout(31 downto 16);
    tmp_V_9_fu_236_p3 <= 
        tmp_V_4_fu_230_p2 when (p_Result_15_fu_222_p3(0) = '1') else 
        tmp_V_8_fu_206_p4;
    tmp_V_fu_182_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_V_6_fu_164_p1));
    trunc_ln738_1_fu_765_p1 <= p_Result_17_fu_753_p5(32 - 1 downto 0);
    trunc_ln738_fu_710_p1 <= p_Result_14_fu_698_p5(32 - 1 downto 0);
    trunc_ln943_1_fu_360_p1 <= l_1_fu_316_p3(8 - 1 downto 0);
    trunc_ln943_fu_305_p1 <= l_fu_261_p3(8 - 1 downto 0);
    trunc_ln944_1_fu_330_p1 <= sub_ln944_1_fu_324_p2(16 - 1 downto 0);
    trunc_ln944_fu_275_p1 <= sub_ln944_fu_269_p2(16 - 1 downto 0);
    trunc_ln947_1_fu_350_p1 <= sub_ln944_1_fu_324_p2(5 - 1 downto 0);
    trunc_ln947_fu_295_p1 <= sub_ln944_fu_269_p2(5 - 1 downto 0);
    xor_ln949_1_fu_555_p2 <= (tmp_12_fu_548_p3 xor ap_const_lv1_1);
    xor_ln949_fu_402_p2 <= (tmp_8_fu_395_p3 xor ap_const_lv1_1);
    zext_ln947_1_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln947_1_reg_889),16));
    zext_ln947_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln947_reg_857),16));
    zext_ln957_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_7_reg_799_pp0_iter2_reg),32));
    zext_ln957_2_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_9_reg_822_pp0_iter2_reg),32));
    zext_ln958_1_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln958_fu_466_p2),64));
    zext_ln958_2_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln958_1_fu_609_p2),64));
    zext_ln958_3_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln958_1_fu_619_p2),64));
    zext_ln958_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln958_fu_456_p2),64));
    zext_ln961_1_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln949_1_fu_585_p3),64));
    zext_ln961_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_432_p3),64));
end behav;
