// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "act_fun.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic act_fun::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic act_fun::ap_const_logic_0 = sc_dt::Log_0;
const bool act_fun::ap_const_boolean_1 = true;
const bool act_fun::ap_const_boolean_0 = false;
const sc_lv<1> act_fun::ap_const_lv1_0 = "0";
const sc_lv<1> act_fun::ap_const_lv1_1 = "1";
const sc_lv<32> act_fun::ap_const_lv32_C0800000 = "11000000100000000000000000000000";
const sc_lv<32> act_fun::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> act_fun::ap_const_lv32_40800000 = "1000000100000000000000000000000";
const sc_lv<64> act_fun::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<64> act_fun::ap_const_lv64_BFF0000000000000 = "1011111111110000000000000000000000000000000000000000000000000000";
const sc_lv<64> act_fun::ap_const_lv64_3FD0000000000000 = "11111111010000000000000000000000000000000000000000000000000000";
const sc_lv<64> act_fun::ap_const_lv64_3FE0000000000000 = "11111111100000000000000000000000000000000000000000000000000000";
const sc_lv<32> act_fun::ap_const_lv32_17 = "10111";
const sc_lv<32> act_fun::ap_const_lv32_1E = "11110";
const sc_lv<8> act_fun::ap_const_lv8_FF = "11111111";
const sc_lv<23> act_fun::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> act_fun::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<5> act_fun::ap_const_lv5_5 = "101";
const sc_lv<5> act_fun::ap_const_lv5_2 = "10";
const sc_lv<5> act_fun::ap_const_lv5_4 = "100";

act_fun::act_fun(sc_module_name name) : sc_module(name), mVcdFile(0) {
    kernel_fptrunc_64bkb_U1 = new kernel_fptrunc_64bkb<1,2,64,32>("kernel_fptrunc_64bkb_U1");
    kernel_fptrunc_64bkb_U1->clk(ap_clk);
    kernel_fptrunc_64bkb_U1->reset(ap_rst);
    kernel_fptrunc_64bkb_U1->din0(reg_110);
    kernel_fptrunc_64bkb_U1->ce(grp_fu_38_ce);
    kernel_fptrunc_64bkb_U1->dout(grp_fu_38_p1);
    kernel_fptrunc_64bkb_U2 = new kernel_fptrunc_64bkb<1,2,64,32>("kernel_fptrunc_64bkb_U2");
    kernel_fptrunc_64bkb_U2->clk(ap_clk);
    kernel_fptrunc_64bkb_U2->reset(ap_rst);
    kernel_fptrunc_64bkb_U2->din0(tmp_23_reg_280);
    kernel_fptrunc_64bkb_U2->ce(grp_fu_41_ce);
    kernel_fptrunc_64bkb_U2->dout(grp_fu_41_p1);
    kernel_fpext_32nscud_U3 = new kernel_fpext_32nscud<1,2,32,64>("kernel_fpext_32nscud_U3");
    kernel_fpext_32nscud_U3->clk(ap_clk);
    kernel_fpext_32nscud_U3->reset(ap_rst);
    kernel_fpext_32nscud_U3->din0(vec_int_reg);
    kernel_fpext_32nscud_U3->ce(grp_fu_44_ce);
    kernel_fpext_32nscud_U3->dout(grp_fu_44_p1);
    kernel_fcmp_32ns_dEe_U4 = new kernel_fcmp_32ns_dEe<1,2,32,32,1>("kernel_fcmp_32ns_dEe_U4");
    kernel_fcmp_32ns_dEe_U4->clk(ap_clk);
    kernel_fcmp_32ns_dEe_U4->reset(ap_rst);
    kernel_fcmp_32ns_dEe_U4->din0(vec_int_reg);
    kernel_fcmp_32ns_dEe_U4->din1(ap_var_for_const0);
    kernel_fcmp_32ns_dEe_U4->ce(grp_fu_48_ce);
    kernel_fcmp_32ns_dEe_U4->opcode(ap_var_for_const1);
    kernel_fcmp_32ns_dEe_U4->dout(grp_fu_48_p2);
    kernel_fcmp_32ns_dEe_U5 = new kernel_fcmp_32ns_dEe<1,2,32,32,1>("kernel_fcmp_32ns_dEe_U5");
    kernel_fcmp_32ns_dEe_U5->clk(ap_clk);
    kernel_fcmp_32ns_dEe_U5->reset(ap_rst);
    kernel_fcmp_32ns_dEe_U5->din0(vec_read_reg_227_pp0_iter1_reg);
    kernel_fcmp_32ns_dEe_U5->din1(ap_var_for_const0);
    kernel_fcmp_32ns_dEe_U5->ce(grp_fu_54_ce);
    kernel_fcmp_32ns_dEe_U5->opcode(ap_var_for_const2);
    kernel_fcmp_32ns_dEe_U5->dout(grp_fu_54_p2);
    kernel_fcmp_32ns_dEe_U6 = new kernel_fcmp_32ns_dEe<1,2,32,32,1>("kernel_fcmp_32ns_dEe_U6");
    kernel_fcmp_32ns_dEe_U6->clk(ap_clk);
    kernel_fcmp_32ns_dEe_U6->reset(ap_rst);
    kernel_fcmp_32ns_dEe_U6->din0(vec_read_reg_227_pp0_iter1_reg);
    kernel_fcmp_32ns_dEe_U6->din1(ap_var_for_const3);
    kernel_fcmp_32ns_dEe_U6->ce(grp_fu_59_ce);
    kernel_fcmp_32ns_dEe_U6->opcode(ap_var_for_const1);
    kernel_fcmp_32ns_dEe_U6->dout(grp_fu_59_p2);
    kernel_fcmp_32ns_dEe_U7 = new kernel_fcmp_32ns_dEe<1,2,32,32,1>("kernel_fcmp_32ns_dEe_U7");
    kernel_fcmp_32ns_dEe_U7->clk(ap_clk);
    kernel_fcmp_32ns_dEe_U7->reset(ap_rst);
    kernel_fcmp_32ns_dEe_U7->din0(vec_read_reg_227_pp0_iter1_reg);
    kernel_fcmp_32ns_dEe_U7->din1(ap_var_for_const3);
    kernel_fcmp_32ns_dEe_U7->ce(grp_fu_64_ce);
    kernel_fcmp_32ns_dEe_U7->opcode(ap_var_for_const2);
    kernel_fcmp_32ns_dEe_U7->dout(grp_fu_64_p2);
    kernel_fcmp_32ns_dEe_U8 = new kernel_fcmp_32ns_dEe<1,2,32,32,1>("kernel_fcmp_32ns_dEe_U8");
    kernel_fcmp_32ns_dEe_U8->clk(ap_clk);
    kernel_fcmp_32ns_dEe_U8->reset(ap_rst);
    kernel_fcmp_32ns_dEe_U8->din0(vec_read_reg_227_pp0_iter1_reg);
    kernel_fcmp_32ns_dEe_U8->din1(ap_var_for_const4);
    kernel_fcmp_32ns_dEe_U8->ce(grp_fu_69_ce);
    kernel_fcmp_32ns_dEe_U8->opcode(ap_var_for_const5);
    kernel_fcmp_32ns_dEe_U8->dout(grp_fu_69_p2);
    kernel_dadd_64ns_eOg_U9 = new kernel_dadd_64ns_eOg<1,6,64,64,64>("kernel_dadd_64ns_eOg_U9");
    kernel_dadd_64ns_eOg_U9->clk(ap_clk);
    kernel_dadd_64ns_eOg_U9->reset(ap_rst);
    kernel_dadd_64ns_eOg_U9->din0(tmp_16_reg_270);
    kernel_dadd_64ns_eOg_U9->din1(grp_fu_74_p1);
    kernel_dadd_64ns_eOg_U9->ce(grp_fu_74_ce);
    kernel_dadd_64ns_eOg_U9->dout(grp_fu_74_p2);
    kernel_dsub_64ns_fYi_U10 = new kernel_dsub_64ns_fYi<1,6,64,64,64>("kernel_dsub_64ns_fYi_U10");
    kernel_dsub_64ns_fYi_U10->clk(ap_clk);
    kernel_dsub_64ns_fYi_U10->reset(ap_rst);
    kernel_dsub_64ns_fYi_U10->din0(ap_var_for_const6);
    kernel_dsub_64ns_fYi_U10->din1(reg_110);
    kernel_dsub_64ns_fYi_U10->ce(grp_fu_80_ce);
    kernel_dsub_64ns_fYi_U10->dout(grp_fu_80_p2);
    kernel_dmul_64ns_g8j_U11 = new kernel_dmul_64ns_g8j<1,6,64,64,64>("kernel_dmul_64ns_g8j_U11");
    kernel_dmul_64ns_g8j_U11->clk(ap_clk);
    kernel_dmul_64ns_g8j_U11->reset(ap_rst);
    kernel_dmul_64ns_g8j_U11->din0(tmp_15_reg_250);
    kernel_dmul_64ns_g8j_U11->din1(ap_var_for_const7);
    kernel_dmul_64ns_g8j_U11->ce(grp_fu_85_ce);
    kernel_dmul_64ns_g8j_U11->dout(grp_fu_85_p2);
    kernel_dmul_64ns_g8j_U12 = new kernel_dmul_64ns_g8j<1,6,64,64,64>("kernel_dmul_64ns_g8j_U12");
    kernel_dmul_64ns_g8j_U12->clk(ap_clk);
    kernel_dmul_64ns_g8j_U12->reset(ap_rst);
    kernel_dmul_64ns_g8j_U12->din0(reg_99);
    kernel_dmul_64ns_g8j_U12->din1(ap_var_for_const8);
    kernel_dmul_64ns_g8j_U12->ce(grp_fu_90_ce);
    kernel_dmul_64ns_g8j_U12->dout(grp_fu_90_p2);
    kernel_dmul_64ns_g8j_U13 = new kernel_dmul_64ns_g8j<1,6,64,64,64>("kernel_dmul_64ns_g8j_U13");
    kernel_dmul_64ns_g8j_U13->clk(ap_clk);
    kernel_dmul_64ns_g8j_U13->reset(ap_rst);
    kernel_dmul_64ns_g8j_U13->din0(reg_105);
    kernel_dmul_64ns_g8j_U13->din1(reg_99_pp0_iter19_reg);
    kernel_dmul_64ns_g8j_U13->ce(grp_fu_95_ce);
    kernel_dmul_64ns_g8j_U13->dout(grp_fu_95_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln10_1_fu_184_p2);
    sensitive << ( xor_ln6_fu_157_p2 );
    sensitive << ( xor_ln8_fu_173_p2 );

    SC_METHOD(thread_and_ln10_2_fu_190_p2);
    sensitive << ( and_ln10_fu_179_p2 );
    sensitive << ( grp_fu_64_p2 );

    SC_METHOD(thread_and_ln10_3_fu_196_p2);
    sensitive << ( and_ln10_2_fu_190_p2 );
    sensitive << ( and_ln10_1_fu_184_p2 );

    SC_METHOD(thread_and_ln10_fu_179_p2);
    sensitive << ( or_ln6_reg_238_pp0_iter2_reg );
    sensitive << ( grp_fu_69_p2 );

    SC_METHOD(thread_and_ln6_fu_151_p2);
    sensitive << ( or_ln6_fu_145_p2 );
    sensitive << ( grp_fu_48_p2 );

    SC_METHOD(thread_and_ln8_1_fu_167_p2);
    sensitive << ( and_ln8_fu_162_p2 );
    sensitive << ( grp_fu_59_p2 );

    SC_METHOD(thread_and_ln8_2_fu_202_p2);
    sensitive << ( xor_ln6_reg_255_pp0_iter32_reg );
    sensitive << ( and_ln8_1_reg_260_pp0_iter32_reg );

    SC_METHOD(thread_and_ln8_fu_162_p2);
    sensitive << ( or_ln6_reg_238_pp0_iter2_reg );
    sensitive << ( grp_fu_54_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_00001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter17);

    SC_METHOD(thread_ap_block_state19_pp0_stage0_iter18);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state20_pp0_stage0_iter19);

    SC_METHOD(thread_ap_block_state21_pp0_stage0_iter20);

    SC_METHOD(thread_ap_block_state22_pp0_stage0_iter21);

    SC_METHOD(thread_ap_block_state23_pp0_stage0_iter22);

    SC_METHOD(thread_ap_block_state24_pp0_stage0_iter23);

    SC_METHOD(thread_ap_block_state25_pp0_stage0_iter24);

    SC_METHOD(thread_ap_block_state26_pp0_stage0_iter25);

    SC_METHOD(thread_ap_block_state27_pp0_stage0_iter26);

    SC_METHOD(thread_ap_block_state28_pp0_stage0_iter27);

    SC_METHOD(thread_ap_block_state29_pp0_stage0_iter28);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state30_pp0_stage0_iter29);

    SC_METHOD(thread_ap_block_state31_pp0_stage0_iter30);

    SC_METHOD(thread_ap_block_state32_pp0_stage0_iter31);

    SC_METHOD(thread_ap_block_state33_pp0_stage0_iter32);

    SC_METHOD(thread_ap_block_state34_pp0_stage0_iter33);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_return);
    sensitive << ( select_ln6_fu_220_p3 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_bitcast_ln6_fu_116_p1);
    sensitive << ( vec_read_reg_227 );

    SC_METHOD(thread_grp_fu_38_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_41_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_44_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_48_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_54_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_59_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_64_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_69_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_74_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_74_p1);
    sensitive << ( and_ln6_reg_244_pp0_iter7_reg );
    sensitive << ( and_ln10_3_reg_265_pp0_iter7_reg );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_80_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_85_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_90_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_95_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_icmp_ln6_1_fu_139_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln6_fu_129_p1 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_icmp_ln6_fu_133_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_fu_119_p4 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_or_ln6_fu_145_p2);
    sensitive << ( icmp_ln6_1_fu_139_p2 );
    sensitive << ( icmp_ln6_fu_133_p2 );

    SC_METHOD(thread_select_ln10_fu_213_p3);
    sensitive << ( and_ln10_3_reg_265_pp0_iter32_reg );
    sensitive << ( grp_fu_41_p1 );
    sensitive << ( select_ln8_fu_206_p3 );

    SC_METHOD(thread_select_ln6_fu_220_p3);
    sensitive << ( and_ln6_reg_244_pp0_iter32_reg );
    sensitive << ( select_ln10_fu_213_p3 );

    SC_METHOD(thread_select_ln8_fu_206_p3);
    sensitive << ( vec_assign_reg_275_pp0_iter32_reg );
    sensitive << ( and_ln8_2_fu_202_p2 );

    SC_METHOD(thread_tmp_fu_119_p4);
    sensitive << ( bitcast_ln6_fu_116_p1 );

    SC_METHOD(thread_trunc_ln6_fu_129_p1);
    sensitive << ( bitcast_ln6_fu_116_p1 );

    SC_METHOD(thread_xor_ln6_fu_157_p2);
    sensitive << ( and_ln6_reg_244_pp0_iter2_reg );

    SC_METHOD(thread_xor_ln8_fu_173_p2);
    sensitive << ( and_ln8_1_fu_167_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const8);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const5);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "act_fun_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, vec, "(port)vec");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_fu_74_p2, "grp_fu_74_p2");
    sc_trace(mVcdFile, reg_99, "reg_99");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11, "ap_block_state12_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12, "ap_block_state13_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13, "ap_block_state14_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14, "ap_block_state15_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15, "ap_block_state16_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16, "ap_block_state17_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter17, "ap_block_state18_pp0_stage0_iter17");
    sc_trace(mVcdFile, ap_block_state19_pp0_stage0_iter18, "ap_block_state19_pp0_stage0_iter18");
    sc_trace(mVcdFile, ap_block_state20_pp0_stage0_iter19, "ap_block_state20_pp0_stage0_iter19");
    sc_trace(mVcdFile, ap_block_state21_pp0_stage0_iter20, "ap_block_state21_pp0_stage0_iter20");
    sc_trace(mVcdFile, ap_block_state22_pp0_stage0_iter21, "ap_block_state22_pp0_stage0_iter21");
    sc_trace(mVcdFile, ap_block_state23_pp0_stage0_iter22, "ap_block_state23_pp0_stage0_iter22");
    sc_trace(mVcdFile, ap_block_state24_pp0_stage0_iter23, "ap_block_state24_pp0_stage0_iter23");
    sc_trace(mVcdFile, ap_block_state25_pp0_stage0_iter24, "ap_block_state25_pp0_stage0_iter24");
    sc_trace(mVcdFile, ap_block_state26_pp0_stage0_iter25, "ap_block_state26_pp0_stage0_iter25");
    sc_trace(mVcdFile, ap_block_state27_pp0_stage0_iter26, "ap_block_state27_pp0_stage0_iter26");
    sc_trace(mVcdFile, ap_block_state28_pp0_stage0_iter27, "ap_block_state28_pp0_stage0_iter27");
    sc_trace(mVcdFile, ap_block_state29_pp0_stage0_iter28, "ap_block_state29_pp0_stage0_iter28");
    sc_trace(mVcdFile, ap_block_state30_pp0_stage0_iter29, "ap_block_state30_pp0_stage0_iter29");
    sc_trace(mVcdFile, ap_block_state31_pp0_stage0_iter30, "ap_block_state31_pp0_stage0_iter30");
    sc_trace(mVcdFile, ap_block_state32_pp0_stage0_iter31, "ap_block_state32_pp0_stage0_iter31");
    sc_trace(mVcdFile, ap_block_state33_pp0_stage0_iter32, "ap_block_state33_pp0_stage0_iter32");
    sc_trace(mVcdFile, ap_block_state34_pp0_stage0_iter33, "ap_block_state34_pp0_stage0_iter33");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, and_ln10_3_reg_265, "and_ln10_3_reg_265");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter12_reg, "and_ln10_3_reg_265_pp0_iter12_reg");
    sc_trace(mVcdFile, and_ln6_reg_244, "and_ln6_reg_244");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter12_reg, "and_ln6_reg_244_pp0_iter12_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter14_reg, "reg_99_pp0_iter14_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter15_reg, "reg_99_pp0_iter15_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter16_reg, "reg_99_pp0_iter16_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter17_reg, "reg_99_pp0_iter17_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter18_reg, "reg_99_pp0_iter18_reg");
    sc_trace(mVcdFile, reg_99_pp0_iter19_reg, "reg_99_pp0_iter19_reg");
    sc_trace(mVcdFile, grp_fu_90_p2, "grp_fu_90_p2");
    sc_trace(mVcdFile, reg_105, "reg_105");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter18_reg, "and_ln10_3_reg_265_pp0_iter18_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter18_reg, "and_ln6_reg_244_pp0_iter18_reg");
    sc_trace(mVcdFile, grp_fu_95_p2, "grp_fu_95_p2");
    sc_trace(mVcdFile, reg_110, "reg_110");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter24_reg, "and_ln10_3_reg_265_pp0_iter24_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter24_reg, "and_ln6_reg_244_pp0_iter24_reg");
    sc_trace(mVcdFile, vec_read_reg_227, "vec_read_reg_227");
    sc_trace(mVcdFile, vec_read_reg_227_pp0_iter1_reg, "vec_read_reg_227_pp0_iter1_reg");
    sc_trace(mVcdFile, or_ln6_fu_145_p2, "or_ln6_fu_145_p2");
    sc_trace(mVcdFile, or_ln6_reg_238, "or_ln6_reg_238");
    sc_trace(mVcdFile, or_ln6_reg_238_pp0_iter2_reg, "or_ln6_reg_238_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln6_fu_151_p2, "and_ln6_fu_151_p2");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter2_reg, "and_ln6_reg_244_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter3_reg, "and_ln6_reg_244_pp0_iter3_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter4_reg, "and_ln6_reg_244_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter5_reg, "and_ln6_reg_244_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter6_reg, "and_ln6_reg_244_pp0_iter6_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter7_reg, "and_ln6_reg_244_pp0_iter7_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter8_reg, "and_ln6_reg_244_pp0_iter8_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter9_reg, "and_ln6_reg_244_pp0_iter9_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter10_reg, "and_ln6_reg_244_pp0_iter10_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter11_reg, "and_ln6_reg_244_pp0_iter11_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter13_reg, "and_ln6_reg_244_pp0_iter13_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter14_reg, "and_ln6_reg_244_pp0_iter14_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter15_reg, "and_ln6_reg_244_pp0_iter15_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter16_reg, "and_ln6_reg_244_pp0_iter16_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter17_reg, "and_ln6_reg_244_pp0_iter17_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter19_reg, "and_ln6_reg_244_pp0_iter19_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter20_reg, "and_ln6_reg_244_pp0_iter20_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter21_reg, "and_ln6_reg_244_pp0_iter21_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter22_reg, "and_ln6_reg_244_pp0_iter22_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter23_reg, "and_ln6_reg_244_pp0_iter23_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter25_reg, "and_ln6_reg_244_pp0_iter25_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter26_reg, "and_ln6_reg_244_pp0_iter26_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter27_reg, "and_ln6_reg_244_pp0_iter27_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter28_reg, "and_ln6_reg_244_pp0_iter28_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter29_reg, "and_ln6_reg_244_pp0_iter29_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter30_reg, "and_ln6_reg_244_pp0_iter30_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter31_reg, "and_ln6_reg_244_pp0_iter31_reg");
    sc_trace(mVcdFile, and_ln6_reg_244_pp0_iter32_reg, "and_ln6_reg_244_pp0_iter32_reg");
    sc_trace(mVcdFile, grp_fu_44_p1, "grp_fu_44_p1");
    sc_trace(mVcdFile, tmp_15_reg_250, "tmp_15_reg_250");
    sc_trace(mVcdFile, xor_ln6_fu_157_p2, "xor_ln6_fu_157_p2");
    sc_trace(mVcdFile, xor_ln6_reg_255, "xor_ln6_reg_255");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter4_reg, "xor_ln6_reg_255_pp0_iter4_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter5_reg, "xor_ln6_reg_255_pp0_iter5_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter6_reg, "xor_ln6_reg_255_pp0_iter6_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter7_reg, "xor_ln6_reg_255_pp0_iter7_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter8_reg, "xor_ln6_reg_255_pp0_iter8_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter9_reg, "xor_ln6_reg_255_pp0_iter9_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter10_reg, "xor_ln6_reg_255_pp0_iter10_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter11_reg, "xor_ln6_reg_255_pp0_iter11_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter12_reg, "xor_ln6_reg_255_pp0_iter12_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter13_reg, "xor_ln6_reg_255_pp0_iter13_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter14_reg, "xor_ln6_reg_255_pp0_iter14_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter15_reg, "xor_ln6_reg_255_pp0_iter15_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter16_reg, "xor_ln6_reg_255_pp0_iter16_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter17_reg, "xor_ln6_reg_255_pp0_iter17_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter18_reg, "xor_ln6_reg_255_pp0_iter18_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter19_reg, "xor_ln6_reg_255_pp0_iter19_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter20_reg, "xor_ln6_reg_255_pp0_iter20_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter21_reg, "xor_ln6_reg_255_pp0_iter21_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter22_reg, "xor_ln6_reg_255_pp0_iter22_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter23_reg, "xor_ln6_reg_255_pp0_iter23_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter24_reg, "xor_ln6_reg_255_pp0_iter24_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter25_reg, "xor_ln6_reg_255_pp0_iter25_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter26_reg, "xor_ln6_reg_255_pp0_iter26_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter27_reg, "xor_ln6_reg_255_pp0_iter27_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter28_reg, "xor_ln6_reg_255_pp0_iter28_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter29_reg, "xor_ln6_reg_255_pp0_iter29_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter30_reg, "xor_ln6_reg_255_pp0_iter30_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter31_reg, "xor_ln6_reg_255_pp0_iter31_reg");
    sc_trace(mVcdFile, xor_ln6_reg_255_pp0_iter32_reg, "xor_ln6_reg_255_pp0_iter32_reg");
    sc_trace(mVcdFile, and_ln8_1_fu_167_p2, "and_ln8_1_fu_167_p2");
    sc_trace(mVcdFile, and_ln8_1_reg_260, "and_ln8_1_reg_260");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter4_reg, "and_ln8_1_reg_260_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter5_reg, "and_ln8_1_reg_260_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter6_reg, "and_ln8_1_reg_260_pp0_iter6_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter7_reg, "and_ln8_1_reg_260_pp0_iter7_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter8_reg, "and_ln8_1_reg_260_pp0_iter8_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter9_reg, "and_ln8_1_reg_260_pp0_iter9_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter10_reg, "and_ln8_1_reg_260_pp0_iter10_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter11_reg, "and_ln8_1_reg_260_pp0_iter11_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter12_reg, "and_ln8_1_reg_260_pp0_iter12_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter13_reg, "and_ln8_1_reg_260_pp0_iter13_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter14_reg, "and_ln8_1_reg_260_pp0_iter14_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter15_reg, "and_ln8_1_reg_260_pp0_iter15_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter16_reg, "and_ln8_1_reg_260_pp0_iter16_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter17_reg, "and_ln8_1_reg_260_pp0_iter17_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter18_reg, "and_ln8_1_reg_260_pp0_iter18_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter19_reg, "and_ln8_1_reg_260_pp0_iter19_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter20_reg, "and_ln8_1_reg_260_pp0_iter20_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter21_reg, "and_ln8_1_reg_260_pp0_iter21_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter22_reg, "and_ln8_1_reg_260_pp0_iter22_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter23_reg, "and_ln8_1_reg_260_pp0_iter23_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter24_reg, "and_ln8_1_reg_260_pp0_iter24_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter25_reg, "and_ln8_1_reg_260_pp0_iter25_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter26_reg, "and_ln8_1_reg_260_pp0_iter26_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter27_reg, "and_ln8_1_reg_260_pp0_iter27_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter28_reg, "and_ln8_1_reg_260_pp0_iter28_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter29_reg, "and_ln8_1_reg_260_pp0_iter29_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter30_reg, "and_ln8_1_reg_260_pp0_iter30_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter31_reg, "and_ln8_1_reg_260_pp0_iter31_reg");
    sc_trace(mVcdFile, and_ln8_1_reg_260_pp0_iter32_reg, "and_ln8_1_reg_260_pp0_iter32_reg");
    sc_trace(mVcdFile, and_ln10_3_fu_196_p2, "and_ln10_3_fu_196_p2");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter4_reg, "and_ln10_3_reg_265_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter5_reg, "and_ln10_3_reg_265_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter6_reg, "and_ln10_3_reg_265_pp0_iter6_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter7_reg, "and_ln10_3_reg_265_pp0_iter7_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter8_reg, "and_ln10_3_reg_265_pp0_iter8_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter9_reg, "and_ln10_3_reg_265_pp0_iter9_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter10_reg, "and_ln10_3_reg_265_pp0_iter10_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter11_reg, "and_ln10_3_reg_265_pp0_iter11_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter13_reg, "and_ln10_3_reg_265_pp0_iter13_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter14_reg, "and_ln10_3_reg_265_pp0_iter14_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter15_reg, "and_ln10_3_reg_265_pp0_iter15_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter16_reg, "and_ln10_3_reg_265_pp0_iter16_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter17_reg, "and_ln10_3_reg_265_pp0_iter17_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter19_reg, "and_ln10_3_reg_265_pp0_iter19_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter20_reg, "and_ln10_3_reg_265_pp0_iter20_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter21_reg, "and_ln10_3_reg_265_pp0_iter21_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter22_reg, "and_ln10_3_reg_265_pp0_iter22_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter23_reg, "and_ln10_3_reg_265_pp0_iter23_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter25_reg, "and_ln10_3_reg_265_pp0_iter25_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter26_reg, "and_ln10_3_reg_265_pp0_iter26_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter27_reg, "and_ln10_3_reg_265_pp0_iter27_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter28_reg, "and_ln10_3_reg_265_pp0_iter28_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter29_reg, "and_ln10_3_reg_265_pp0_iter29_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter30_reg, "and_ln10_3_reg_265_pp0_iter30_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter31_reg, "and_ln10_3_reg_265_pp0_iter31_reg");
    sc_trace(mVcdFile, and_ln10_3_reg_265_pp0_iter32_reg, "and_ln10_3_reg_265_pp0_iter32_reg");
    sc_trace(mVcdFile, grp_fu_85_p2, "grp_fu_85_p2");
    sc_trace(mVcdFile, tmp_16_reg_270, "tmp_16_reg_270");
    sc_trace(mVcdFile, grp_fu_38_p1, "grp_fu_38_p1");
    sc_trace(mVcdFile, vec_assign_reg_275, "vec_assign_reg_275");
    sc_trace(mVcdFile, vec_assign_reg_275_pp0_iter28_reg, "vec_assign_reg_275_pp0_iter28_reg");
    sc_trace(mVcdFile, vec_assign_reg_275_pp0_iter29_reg, "vec_assign_reg_275_pp0_iter29_reg");
    sc_trace(mVcdFile, vec_assign_reg_275_pp0_iter30_reg, "vec_assign_reg_275_pp0_iter30_reg");
    sc_trace(mVcdFile, vec_assign_reg_275_pp0_iter31_reg, "vec_assign_reg_275_pp0_iter31_reg");
    sc_trace(mVcdFile, vec_assign_reg_275_pp0_iter32_reg, "vec_assign_reg_275_pp0_iter32_reg");
    sc_trace(mVcdFile, grp_fu_80_p2, "grp_fu_80_p2");
    sc_trace(mVcdFile, tmp_23_reg_280, "tmp_23_reg_280");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_fu_74_p1, "grp_fu_74_p1");
    sc_trace(mVcdFile, bitcast_ln6_fu_116_p1, "bitcast_ln6_fu_116_p1");
    sc_trace(mVcdFile, tmp_fu_119_p4, "tmp_fu_119_p4");
    sc_trace(mVcdFile, trunc_ln6_fu_129_p1, "trunc_ln6_fu_129_p1");
    sc_trace(mVcdFile, icmp_ln6_1_fu_139_p2, "icmp_ln6_1_fu_139_p2");
    sc_trace(mVcdFile, icmp_ln6_fu_133_p2, "icmp_ln6_fu_133_p2");
    sc_trace(mVcdFile, grp_fu_48_p2, "grp_fu_48_p2");
    sc_trace(mVcdFile, grp_fu_54_p2, "grp_fu_54_p2");
    sc_trace(mVcdFile, and_ln8_fu_162_p2, "and_ln8_fu_162_p2");
    sc_trace(mVcdFile, grp_fu_59_p2, "grp_fu_59_p2");
    sc_trace(mVcdFile, grp_fu_69_p2, "grp_fu_69_p2");
    sc_trace(mVcdFile, xor_ln8_fu_173_p2, "xor_ln8_fu_173_p2");
    sc_trace(mVcdFile, and_ln10_fu_179_p2, "and_ln10_fu_179_p2");
    sc_trace(mVcdFile, grp_fu_64_p2, "grp_fu_64_p2");
    sc_trace(mVcdFile, and_ln10_2_fu_190_p2, "and_ln10_2_fu_190_p2");
    sc_trace(mVcdFile, and_ln10_1_fu_184_p2, "and_ln10_1_fu_184_p2");
    sc_trace(mVcdFile, and_ln8_2_fu_202_p2, "and_ln8_2_fu_202_p2");
    sc_trace(mVcdFile, grp_fu_41_p1, "grp_fu_41_p1");
    sc_trace(mVcdFile, select_ln8_fu_206_p3, "select_ln8_fu_206_p3");
    sc_trace(mVcdFile, select_ln10_fu_213_p3, "select_ln10_fu_213_p3");
    sc_trace(mVcdFile, grp_fu_38_ce, "grp_fu_38_ce");
    sc_trace(mVcdFile, grp_fu_41_ce, "grp_fu_41_ce");
    sc_trace(mVcdFile, grp_fu_44_ce, "grp_fu_44_ce");
    sc_trace(mVcdFile, grp_fu_48_ce, "grp_fu_48_ce");
    sc_trace(mVcdFile, ap_block_pp0_stage0_00001, "ap_block_pp0_stage0_00001");
    sc_trace(mVcdFile, grp_fu_54_ce, "grp_fu_54_ce");
    sc_trace(mVcdFile, grp_fu_59_ce, "grp_fu_59_ce");
    sc_trace(mVcdFile, grp_fu_64_ce, "grp_fu_64_ce");
    sc_trace(mVcdFile, grp_fu_69_ce, "grp_fu_69_ce");
    sc_trace(mVcdFile, grp_fu_74_ce, "grp_fu_74_ce");
    sc_trace(mVcdFile, grp_fu_80_ce, "grp_fu_80_ce");
    sc_trace(mVcdFile, grp_fu_85_ce, "grp_fu_85_ce");
    sc_trace(mVcdFile, grp_fu_90_ce, "grp_fu_90_ce");
    sc_trace(mVcdFile, grp_fu_95_ce, "grp_fu_95_ce");
    sc_trace(mVcdFile, select_ln6_fu_220_p3, "select_ln6_fu_220_p3");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, vec_int_reg, "vec_int_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
#endif

    }
}

act_fun::~act_fun() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete kernel_fptrunc_64bkb_U1;
    delete kernel_fptrunc_64bkb_U2;
    delete kernel_fpext_32nscud_U3;
    delete kernel_fcmp_32ns_dEe_U4;
    delete kernel_fcmp_32ns_dEe_U5;
    delete kernel_fcmp_32ns_dEe_U6;
    delete kernel_fcmp_32ns_dEe_U7;
    delete kernel_fcmp_32ns_dEe_U8;
    delete kernel_dadd_64ns_eOg_U9;
    delete kernel_dsub_64ns_fYi_U10;
    delete kernel_dmul_64ns_g8j_U11;
    delete kernel_dmul_64ns_g8j_U12;
    delete kernel_dmul_64ns_g8j_U13;
}

void act_fun::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_C0800000;
}

void act_fun::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv32_0;
}

void act_fun::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv32_40800000;
}

void act_fun::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_lv64_3FF0000000000000;
}

void act_fun::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv64_3FD0000000000000;
}

void act_fun::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv64_3FE0000000000000;
}

void act_fun::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_5;
}

void act_fun::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_2;
}

void act_fun::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv5_4;
}

void act_fun::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        and_ln10_3_reg_265 = and_ln10_3_fu_196_p2.read();
        and_ln8_1_reg_260 = and_ln8_1_fu_167_p2.read();
        xor_ln6_reg_255 = xor_ln6_fu_157_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        and_ln10_3_reg_265_pp0_iter10_reg = and_ln10_3_reg_265_pp0_iter9_reg.read();
        and_ln10_3_reg_265_pp0_iter11_reg = and_ln10_3_reg_265_pp0_iter10_reg.read();
        and_ln10_3_reg_265_pp0_iter12_reg = and_ln10_3_reg_265_pp0_iter11_reg.read();
        and_ln10_3_reg_265_pp0_iter13_reg = and_ln10_3_reg_265_pp0_iter12_reg.read();
        and_ln10_3_reg_265_pp0_iter14_reg = and_ln10_3_reg_265_pp0_iter13_reg.read();
        and_ln10_3_reg_265_pp0_iter15_reg = and_ln10_3_reg_265_pp0_iter14_reg.read();
        and_ln10_3_reg_265_pp0_iter16_reg = and_ln10_3_reg_265_pp0_iter15_reg.read();
        and_ln10_3_reg_265_pp0_iter17_reg = and_ln10_3_reg_265_pp0_iter16_reg.read();
        and_ln10_3_reg_265_pp0_iter18_reg = and_ln10_3_reg_265_pp0_iter17_reg.read();
        and_ln10_3_reg_265_pp0_iter19_reg = and_ln10_3_reg_265_pp0_iter18_reg.read();
        and_ln10_3_reg_265_pp0_iter20_reg = and_ln10_3_reg_265_pp0_iter19_reg.read();
        and_ln10_3_reg_265_pp0_iter21_reg = and_ln10_3_reg_265_pp0_iter20_reg.read();
        and_ln10_3_reg_265_pp0_iter22_reg = and_ln10_3_reg_265_pp0_iter21_reg.read();
        and_ln10_3_reg_265_pp0_iter23_reg = and_ln10_3_reg_265_pp0_iter22_reg.read();
        and_ln10_3_reg_265_pp0_iter24_reg = and_ln10_3_reg_265_pp0_iter23_reg.read();
        and_ln10_3_reg_265_pp0_iter25_reg = and_ln10_3_reg_265_pp0_iter24_reg.read();
        and_ln10_3_reg_265_pp0_iter26_reg = and_ln10_3_reg_265_pp0_iter25_reg.read();
        and_ln10_3_reg_265_pp0_iter27_reg = and_ln10_3_reg_265_pp0_iter26_reg.read();
        and_ln10_3_reg_265_pp0_iter28_reg = and_ln10_3_reg_265_pp0_iter27_reg.read();
        and_ln10_3_reg_265_pp0_iter29_reg = and_ln10_3_reg_265_pp0_iter28_reg.read();
        and_ln10_3_reg_265_pp0_iter30_reg = and_ln10_3_reg_265_pp0_iter29_reg.read();
        and_ln10_3_reg_265_pp0_iter31_reg = and_ln10_3_reg_265_pp0_iter30_reg.read();
        and_ln10_3_reg_265_pp0_iter32_reg = and_ln10_3_reg_265_pp0_iter31_reg.read();
        and_ln10_3_reg_265_pp0_iter4_reg = and_ln10_3_reg_265.read();
        and_ln10_3_reg_265_pp0_iter5_reg = and_ln10_3_reg_265_pp0_iter4_reg.read();
        and_ln10_3_reg_265_pp0_iter6_reg = and_ln10_3_reg_265_pp0_iter5_reg.read();
        and_ln10_3_reg_265_pp0_iter7_reg = and_ln10_3_reg_265_pp0_iter6_reg.read();
        and_ln10_3_reg_265_pp0_iter8_reg = and_ln10_3_reg_265_pp0_iter7_reg.read();
        and_ln10_3_reg_265_pp0_iter9_reg = and_ln10_3_reg_265_pp0_iter8_reg.read();
        and_ln6_reg_244 = and_ln6_fu_151_p2.read();
        and_ln6_reg_244_pp0_iter10_reg = and_ln6_reg_244_pp0_iter9_reg.read();
        and_ln6_reg_244_pp0_iter11_reg = and_ln6_reg_244_pp0_iter10_reg.read();
        and_ln6_reg_244_pp0_iter12_reg = and_ln6_reg_244_pp0_iter11_reg.read();
        and_ln6_reg_244_pp0_iter13_reg = and_ln6_reg_244_pp0_iter12_reg.read();
        and_ln6_reg_244_pp0_iter14_reg = and_ln6_reg_244_pp0_iter13_reg.read();
        and_ln6_reg_244_pp0_iter15_reg = and_ln6_reg_244_pp0_iter14_reg.read();
        and_ln6_reg_244_pp0_iter16_reg = and_ln6_reg_244_pp0_iter15_reg.read();
        and_ln6_reg_244_pp0_iter17_reg = and_ln6_reg_244_pp0_iter16_reg.read();
        and_ln6_reg_244_pp0_iter18_reg = and_ln6_reg_244_pp0_iter17_reg.read();
        and_ln6_reg_244_pp0_iter19_reg = and_ln6_reg_244_pp0_iter18_reg.read();
        and_ln6_reg_244_pp0_iter20_reg = and_ln6_reg_244_pp0_iter19_reg.read();
        and_ln6_reg_244_pp0_iter21_reg = and_ln6_reg_244_pp0_iter20_reg.read();
        and_ln6_reg_244_pp0_iter22_reg = and_ln6_reg_244_pp0_iter21_reg.read();
        and_ln6_reg_244_pp0_iter23_reg = and_ln6_reg_244_pp0_iter22_reg.read();
        and_ln6_reg_244_pp0_iter24_reg = and_ln6_reg_244_pp0_iter23_reg.read();
        and_ln6_reg_244_pp0_iter25_reg = and_ln6_reg_244_pp0_iter24_reg.read();
        and_ln6_reg_244_pp0_iter26_reg = and_ln6_reg_244_pp0_iter25_reg.read();
        and_ln6_reg_244_pp0_iter27_reg = and_ln6_reg_244_pp0_iter26_reg.read();
        and_ln6_reg_244_pp0_iter28_reg = and_ln6_reg_244_pp0_iter27_reg.read();
        and_ln6_reg_244_pp0_iter29_reg = and_ln6_reg_244_pp0_iter28_reg.read();
        and_ln6_reg_244_pp0_iter2_reg = and_ln6_reg_244.read();
        and_ln6_reg_244_pp0_iter30_reg = and_ln6_reg_244_pp0_iter29_reg.read();
        and_ln6_reg_244_pp0_iter31_reg = and_ln6_reg_244_pp0_iter30_reg.read();
        and_ln6_reg_244_pp0_iter32_reg = and_ln6_reg_244_pp0_iter31_reg.read();
        and_ln6_reg_244_pp0_iter3_reg = and_ln6_reg_244_pp0_iter2_reg.read();
        and_ln6_reg_244_pp0_iter4_reg = and_ln6_reg_244_pp0_iter3_reg.read();
        and_ln6_reg_244_pp0_iter5_reg = and_ln6_reg_244_pp0_iter4_reg.read();
        and_ln6_reg_244_pp0_iter6_reg = and_ln6_reg_244_pp0_iter5_reg.read();
        and_ln6_reg_244_pp0_iter7_reg = and_ln6_reg_244_pp0_iter6_reg.read();
        and_ln6_reg_244_pp0_iter8_reg = and_ln6_reg_244_pp0_iter7_reg.read();
        and_ln6_reg_244_pp0_iter9_reg = and_ln6_reg_244_pp0_iter8_reg.read();
        and_ln8_1_reg_260_pp0_iter10_reg = and_ln8_1_reg_260_pp0_iter9_reg.read();
        and_ln8_1_reg_260_pp0_iter11_reg = and_ln8_1_reg_260_pp0_iter10_reg.read();
        and_ln8_1_reg_260_pp0_iter12_reg = and_ln8_1_reg_260_pp0_iter11_reg.read();
        and_ln8_1_reg_260_pp0_iter13_reg = and_ln8_1_reg_260_pp0_iter12_reg.read();
        and_ln8_1_reg_260_pp0_iter14_reg = and_ln8_1_reg_260_pp0_iter13_reg.read();
        and_ln8_1_reg_260_pp0_iter15_reg = and_ln8_1_reg_260_pp0_iter14_reg.read();
        and_ln8_1_reg_260_pp0_iter16_reg = and_ln8_1_reg_260_pp0_iter15_reg.read();
        and_ln8_1_reg_260_pp0_iter17_reg = and_ln8_1_reg_260_pp0_iter16_reg.read();
        and_ln8_1_reg_260_pp0_iter18_reg = and_ln8_1_reg_260_pp0_iter17_reg.read();
        and_ln8_1_reg_260_pp0_iter19_reg = and_ln8_1_reg_260_pp0_iter18_reg.read();
        and_ln8_1_reg_260_pp0_iter20_reg = and_ln8_1_reg_260_pp0_iter19_reg.read();
        and_ln8_1_reg_260_pp0_iter21_reg = and_ln8_1_reg_260_pp0_iter20_reg.read();
        and_ln8_1_reg_260_pp0_iter22_reg = and_ln8_1_reg_260_pp0_iter21_reg.read();
        and_ln8_1_reg_260_pp0_iter23_reg = and_ln8_1_reg_260_pp0_iter22_reg.read();
        and_ln8_1_reg_260_pp0_iter24_reg = and_ln8_1_reg_260_pp0_iter23_reg.read();
        and_ln8_1_reg_260_pp0_iter25_reg = and_ln8_1_reg_260_pp0_iter24_reg.read();
        and_ln8_1_reg_260_pp0_iter26_reg = and_ln8_1_reg_260_pp0_iter25_reg.read();
        and_ln8_1_reg_260_pp0_iter27_reg = and_ln8_1_reg_260_pp0_iter26_reg.read();
        and_ln8_1_reg_260_pp0_iter28_reg = and_ln8_1_reg_260_pp0_iter27_reg.read();
        and_ln8_1_reg_260_pp0_iter29_reg = and_ln8_1_reg_260_pp0_iter28_reg.read();
        and_ln8_1_reg_260_pp0_iter30_reg = and_ln8_1_reg_260_pp0_iter29_reg.read();
        and_ln8_1_reg_260_pp0_iter31_reg = and_ln8_1_reg_260_pp0_iter30_reg.read();
        and_ln8_1_reg_260_pp0_iter32_reg = and_ln8_1_reg_260_pp0_iter31_reg.read();
        and_ln8_1_reg_260_pp0_iter4_reg = and_ln8_1_reg_260.read();
        and_ln8_1_reg_260_pp0_iter5_reg = and_ln8_1_reg_260_pp0_iter4_reg.read();
        and_ln8_1_reg_260_pp0_iter6_reg = and_ln8_1_reg_260_pp0_iter5_reg.read();
        and_ln8_1_reg_260_pp0_iter7_reg = and_ln8_1_reg_260_pp0_iter6_reg.read();
        and_ln8_1_reg_260_pp0_iter8_reg = and_ln8_1_reg_260_pp0_iter7_reg.read();
        and_ln8_1_reg_260_pp0_iter9_reg = and_ln8_1_reg_260_pp0_iter8_reg.read();
        or_ln6_reg_238 = or_ln6_fu_145_p2.read();
        or_ln6_reg_238_pp0_iter2_reg = or_ln6_reg_238.read();
        reg_99_pp0_iter14_reg = reg_99.read();
        reg_99_pp0_iter15_reg = reg_99_pp0_iter14_reg.read();
        reg_99_pp0_iter16_reg = reg_99_pp0_iter15_reg.read();
        reg_99_pp0_iter17_reg = reg_99_pp0_iter16_reg.read();
        reg_99_pp0_iter18_reg = reg_99_pp0_iter17_reg.read();
        reg_99_pp0_iter19_reg = reg_99_pp0_iter18_reg.read();
        tmp_15_reg_250 = grp_fu_44_p1.read();
        vec_assign_reg_275_pp0_iter28_reg = vec_assign_reg_275.read();
        vec_assign_reg_275_pp0_iter29_reg = vec_assign_reg_275_pp0_iter28_reg.read();
        vec_assign_reg_275_pp0_iter30_reg = vec_assign_reg_275_pp0_iter29_reg.read();
        vec_assign_reg_275_pp0_iter31_reg = vec_assign_reg_275_pp0_iter30_reg.read();
        vec_assign_reg_275_pp0_iter32_reg = vec_assign_reg_275_pp0_iter31_reg.read();
        vec_read_reg_227 = vec_int_reg.read();
        vec_read_reg_227_pp0_iter1_reg = vec_read_reg_227.read();
        xor_ln6_reg_255_pp0_iter10_reg = xor_ln6_reg_255_pp0_iter9_reg.read();
        xor_ln6_reg_255_pp0_iter11_reg = xor_ln6_reg_255_pp0_iter10_reg.read();
        xor_ln6_reg_255_pp0_iter12_reg = xor_ln6_reg_255_pp0_iter11_reg.read();
        xor_ln6_reg_255_pp0_iter13_reg = xor_ln6_reg_255_pp0_iter12_reg.read();
        xor_ln6_reg_255_pp0_iter14_reg = xor_ln6_reg_255_pp0_iter13_reg.read();
        xor_ln6_reg_255_pp0_iter15_reg = xor_ln6_reg_255_pp0_iter14_reg.read();
        xor_ln6_reg_255_pp0_iter16_reg = xor_ln6_reg_255_pp0_iter15_reg.read();
        xor_ln6_reg_255_pp0_iter17_reg = xor_ln6_reg_255_pp0_iter16_reg.read();
        xor_ln6_reg_255_pp0_iter18_reg = xor_ln6_reg_255_pp0_iter17_reg.read();
        xor_ln6_reg_255_pp0_iter19_reg = xor_ln6_reg_255_pp0_iter18_reg.read();
        xor_ln6_reg_255_pp0_iter20_reg = xor_ln6_reg_255_pp0_iter19_reg.read();
        xor_ln6_reg_255_pp0_iter21_reg = xor_ln6_reg_255_pp0_iter20_reg.read();
        xor_ln6_reg_255_pp0_iter22_reg = xor_ln6_reg_255_pp0_iter21_reg.read();
        xor_ln6_reg_255_pp0_iter23_reg = xor_ln6_reg_255_pp0_iter22_reg.read();
        xor_ln6_reg_255_pp0_iter24_reg = xor_ln6_reg_255_pp0_iter23_reg.read();
        xor_ln6_reg_255_pp0_iter25_reg = xor_ln6_reg_255_pp0_iter24_reg.read();
        xor_ln6_reg_255_pp0_iter26_reg = xor_ln6_reg_255_pp0_iter25_reg.read();
        xor_ln6_reg_255_pp0_iter27_reg = xor_ln6_reg_255_pp0_iter26_reg.read();
        xor_ln6_reg_255_pp0_iter28_reg = xor_ln6_reg_255_pp0_iter27_reg.read();
        xor_ln6_reg_255_pp0_iter29_reg = xor_ln6_reg_255_pp0_iter28_reg.read();
        xor_ln6_reg_255_pp0_iter30_reg = xor_ln6_reg_255_pp0_iter29_reg.read();
        xor_ln6_reg_255_pp0_iter31_reg = xor_ln6_reg_255_pp0_iter30_reg.read();
        xor_ln6_reg_255_pp0_iter32_reg = xor_ln6_reg_255_pp0_iter31_reg.read();
        xor_ln6_reg_255_pp0_iter4_reg = xor_ln6_reg_255.read();
        xor_ln6_reg_255_pp0_iter5_reg = xor_ln6_reg_255_pp0_iter4_reg.read();
        xor_ln6_reg_255_pp0_iter6_reg = xor_ln6_reg_255_pp0_iter5_reg.read();
        xor_ln6_reg_255_pp0_iter7_reg = xor_ln6_reg_255_pp0_iter6_reg.read();
        xor_ln6_reg_255_pp0_iter8_reg = xor_ln6_reg_255_pp0_iter7_reg.read();
        xor_ln6_reg_255_pp0_iter9_reg = xor_ln6_reg_255_pp0_iter8_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = select_ln6_fu_220_p3.read();
    }
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln10_3_reg_265_pp0_iter18_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter18_reg.read()) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter18_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, and_ln10_3_reg_265_pp0_iter18_reg.read()) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)))) {
        reg_105 = grp_fu_90_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln10_3_reg_265_pp0_iter24_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter24_reg.read()) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter24_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, and_ln10_3_reg_265_pp0_iter24_reg.read()) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)))) {
        reg_110 = grp_fu_95_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(and_ln10_3_reg_265_pp0_iter12_reg.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter12_reg.read()) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter12_reg.read()) && 
  esl_seteq<1,1,1>(and_ln10_3_reg_265_pp0_iter12_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1)))) {
        reg_99 = grp_fu_74_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter6_reg.read()) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        tmp_16_reg_270 = grp_fu_85_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln10_3_reg_265_pp0_iter30_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter30_reg.read()) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        tmp_23_reg_280 = grp_fu_80_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln10_3_reg_265_pp0_iter26_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter26_reg.read()) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        vec_assign_reg_275 = grp_fu_38_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        vec_int_reg = vec.read();
    }
}

void act_fun::thread_and_ln10_1_fu_184_p2() {
    and_ln10_1_fu_184_p2 = (xor_ln8_fu_173_p2.read() & xor_ln6_fu_157_p2.read());
}

void act_fun::thread_and_ln10_2_fu_190_p2() {
    and_ln10_2_fu_190_p2 = (and_ln10_fu_179_p2.read() & grp_fu_64_p2.read());
}

void act_fun::thread_and_ln10_3_fu_196_p2() {
    and_ln10_3_fu_196_p2 = (and_ln10_2_fu_190_p2.read() & and_ln10_1_fu_184_p2.read());
}

void act_fun::thread_and_ln10_fu_179_p2() {
    and_ln10_fu_179_p2 = (or_ln6_reg_238_pp0_iter2_reg.read() & grp_fu_69_p2.read());
}

void act_fun::thread_and_ln6_fu_151_p2() {
    and_ln6_fu_151_p2 = (or_ln6_fu_145_p2.read() & grp_fu_48_p2.read());
}

void act_fun::thread_and_ln8_1_fu_167_p2() {
    and_ln8_1_fu_167_p2 = (and_ln8_fu_162_p2.read() & grp_fu_59_p2.read());
}

void act_fun::thread_and_ln8_2_fu_202_p2() {
    and_ln8_2_fu_202_p2 = (and_ln8_1_reg_260_pp0_iter32_reg.read() & xor_ln6_reg_255_pp0_iter32_reg.read());
}

void act_fun::thread_and_ln8_fu_162_p2() {
    and_ln8_fu_162_p2 = (or_ln6_reg_238_pp0_iter2_reg.read() & grp_fu_54_p2.read());
}

void act_fun::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_pp0_stage0_00001() {
    ap_block_pp0_stage0_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state12_pp0_stage0_iter11() {
    ap_block_state12_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state13_pp0_stage0_iter12() {
    ap_block_state13_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state14_pp0_stage0_iter13() {
    ap_block_state14_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state15_pp0_stage0_iter14() {
    ap_block_state15_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state16_pp0_stage0_iter15() {
    ap_block_state16_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state17_pp0_stage0_iter16() {
    ap_block_state17_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state18_pp0_stage0_iter17() {
    ap_block_state18_pp0_stage0_iter17 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state19_pp0_stage0_iter18() {
    ap_block_state19_pp0_stage0_iter18 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state20_pp0_stage0_iter19() {
    ap_block_state20_pp0_stage0_iter19 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state21_pp0_stage0_iter20() {
    ap_block_state21_pp0_stage0_iter20 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state22_pp0_stage0_iter21() {
    ap_block_state22_pp0_stage0_iter21 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state23_pp0_stage0_iter22() {
    ap_block_state23_pp0_stage0_iter22 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state24_pp0_stage0_iter23() {
    ap_block_state24_pp0_stage0_iter23 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state25_pp0_stage0_iter24() {
    ap_block_state25_pp0_stage0_iter24 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state26_pp0_stage0_iter25() {
    ap_block_state26_pp0_stage0_iter25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state27_pp0_stage0_iter26() {
    ap_block_state27_pp0_stage0_iter26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state28_pp0_stage0_iter27() {
    ap_block_state28_pp0_stage0_iter27 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state29_pp0_stage0_iter28() {
    ap_block_state29_pp0_stage0_iter28 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state30_pp0_stage0_iter29() {
    ap_block_state30_pp0_stage0_iter29 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state31_pp0_stage0_iter30() {
    ap_block_state31_pp0_stage0_iter30 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state32_pp0_stage0_iter31() {
    ap_block_state32_pp0_stage0_iter31 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state33_pp0_stage0_iter32() {
    ap_block_state33_pp0_stage0_iter32 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state34_pp0_stage0_iter33() {
    ap_block_state34_pp0_stage0_iter33 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void act_fun::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = select_ln6_fu_220_p3.read();
    }
}

void act_fun::thread_bitcast_ln6_fu_116_p1() {
    bitcast_ln6_fu_116_p1 = vec_read_reg_227.read();
}

void act_fun::thread_grp_fu_38_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_38_ce = ap_const_logic_1;
    } else {
        grp_fu_38_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_41_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_41_ce = ap_const_logic_1;
    } else {
        grp_fu_41_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_44_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_44_ce = ap_const_logic_1;
    } else {
        grp_fu_44_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_48_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_48_ce = ap_const_logic_1;
    } else {
        grp_fu_48_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_54_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_54_ce = ap_const_logic_1;
    } else {
        grp_fu_54_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_59_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_59_ce = ap_const_logic_1;
    } else {
        grp_fu_59_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_64_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_64_ce = ap_const_logic_1;
    } else {
        grp_fu_64_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_69_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_69_ce = ap_const_logic_1;
    } else {
        grp_fu_69_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_74_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_74_ce = ap_const_logic_1;
    } else {
        grp_fu_74_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_74_p1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, and_ln6_reg_244_pp0_iter7_reg.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, and_ln10_3_reg_265_pp0_iter7_reg.read())) {
            grp_fu_74_p1 = ap_const_lv64_BFF0000000000000;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, and_ln10_3_reg_265_pp0_iter7_reg.read())) {
            grp_fu_74_p1 = ap_const_lv64_3FF0000000000000;
        } else {
            grp_fu_74_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_74_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void act_fun::thread_grp_fu_80_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_80_ce = ap_const_logic_1;
    } else {
        grp_fu_80_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_85_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_85_ce = ap_const_logic_1;
    } else {
        grp_fu_85_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_90_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_90_ce = ap_const_logic_1;
    } else {
        grp_fu_90_ce = ap_const_logic_0;
    }
}

void act_fun::thread_grp_fu_95_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_95_ce = ap_const_logic_1;
    } else {
        grp_fu_95_ce = ap_const_logic_0;
    }
}

void act_fun::thread_icmp_ln6_1_fu_139_p2() {
    icmp_ln6_1_fu_139_p2 = (!trunc_ln6_fu_129_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln6_fu_129_p1.read() == ap_const_lv23_0);
}

void act_fun::thread_icmp_ln6_fu_133_p2() {
    icmp_ln6_fu_133_p2 = (!tmp_fu_119_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_119_p4.read() != ap_const_lv8_FF);
}

void act_fun::thread_or_ln6_fu_145_p2() {
    or_ln6_fu_145_p2 = (icmp_ln6_1_fu_139_p2.read() | icmp_ln6_fu_133_p2.read());
}

void act_fun::thread_select_ln10_fu_213_p3() {
    select_ln10_fu_213_p3 = (!and_ln10_3_reg_265_pp0_iter32_reg.read()[0].is_01())? sc_lv<32>(): ((and_ln10_3_reg_265_pp0_iter32_reg.read()[0].to_bool())? grp_fu_41_p1.read(): select_ln8_fu_206_p3.read());
}

void act_fun::thread_select_ln6_fu_220_p3() {
    select_ln6_fu_220_p3 = (!and_ln6_reg_244_pp0_iter32_reg.read()[0].is_01())? sc_lv<32>(): ((and_ln6_reg_244_pp0_iter32_reg.read()[0].to_bool())? ap_const_lv32_0: select_ln10_fu_213_p3.read());
}

void act_fun::thread_select_ln8_fu_206_p3() {
    select_ln8_fu_206_p3 = (!and_ln8_2_fu_202_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln8_2_fu_202_p2.read()[0].to_bool())? vec_assign_reg_275_pp0_iter32_reg.read(): ap_const_lv32_3F800000);
}

void act_fun::thread_tmp_fu_119_p4() {
    tmp_fu_119_p4 = bitcast_ln6_fu_116_p1.read().range(30, 23);
}

void act_fun::thread_trunc_ln6_fu_129_p1() {
    trunc_ln6_fu_129_p1 = bitcast_ln6_fu_116_p1.read().range(23-1, 0);
}

void act_fun::thread_xor_ln6_fu_157_p2() {
    xor_ln6_fu_157_p2 = (and_ln6_reg_244_pp0_iter2_reg.read() ^ ap_const_lv1_1);
}

void act_fun::thread_xor_ln8_fu_173_p2() {
    xor_ln8_fu_173_p2 = (and_ln8_1_fu_167_p2.read() ^ ap_const_lv1_1);
}

}

